var ATTACK_MODE=true,POTION_TARGET=500,POTION_MIN=40,MAX_ATTACK_RATIO=0.24;
var LEADER="Jazwyn",TANK="Jazwyn",MERCHANT="puppygirl",PARTY=["Jazwyn","Sarene","Zarook"];
var LADDER=[[1,"goo"],[4,"bee"],[8,"crab"],[12,"snake"],[16,"armadillo"],[20,"arcticbee"],[24,"porcupine"],[28,"croc"],[30,"tortoise"],[32,"bat"],[42,"spider"],[50,"scorpion"],[54,"boar"],[60,"bigbird"],[66,"gscorpion"],[72,"wolf"],[78,"dryad"]];
var HOME=["US","II"],FARM=["US","III"],FORM_NEAR=18,FORM_FAR=40,FORM_SMART=220,FORM_REANCHOR=70,BUSY_MS=60000,SMART_STUCK_MS=20000,PSAY_MS=1600,FARM_GO_MS=10000,FARM_NEAR=60,STATE_MS=20000,GEAR_AD_MS=20000;
var busy=false,busy_since=0,farm=null,farm_ovr=null,last_lv=character.level,is_lead=character.name===LEADER;
var HK="hold_"+character.name,rally=false,hold_done=false,hooks=null,last_lead_angle=null,form_anchor=null,form_slot=null,last_s=new Date(0),last_s_msg="",last_psay=new Date(0),last_farm_go=new Date(0),last_xy=null,last_xy_t=0,gift_ttl={},last_gear_ad=new Date(0);
function ls(v){try{if(v==null)return localStorage.getItem(HK)==="1";localStorage.setItem(HK,v?"1":"0")}catch(e){return false}}
var hold=!!ls(),last_pots_say=new Date(0),last_gold=new Date(0),last_invite=new Date(0),seen={};
function go_s(s){if(parent.server_region===s[0]&&parent.server_identifier===s[1])return false;try{change_server(s[0],s[1])}catch(e){}return true}
function pot(kind){return kind==="hp"?(character.level>=30?"hpot1":"hpot0"):(character.level>=30?"mpot1":"mpot0")}
function bump(n,lv,hp){var s=seen[n]||(seen[n]={l:0,h:0});if(lv>s.l)s.l=lv;if(hp>s.h)s.h=hp;return s}
function att_cap(){return Math.max(8,Math.floor(bump(character.name,character.level,character.max_hp).h*MAX_ATTACK_RATIO))}
function price(name){return(G.items[name]&&G.items[name].g)||20}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function is_pot(it){return it&&(it.name.indexOf("hpot")===0||it.name.indexOf("mpot")===0)}
function handle_gear_offer(d){var i,it,ok=0,id,slot;if(!d||!d.name)return;id=d.id||d.name;gift_ttl[id]={name:d.name,expire_ms:Date.now()+120000};(async function(){await equip_pending();for(i=0;i<character.items.length;i++){it=character.items[i];if(it&&it.name===d.name&&(it.level||0)===(d.level||0)){try{await equip(i,d.slot||undefined)}catch(e){}break}}await equip_pending();slot=d.slot;if(slot&&character.slots[slot]&&character.slots[slot].name===d.name&&(character.slots[slot].level||0)===(d.level||0))ok=1;try{send_cm(MERCHANT,{gear_got:1,id:d.id,name:d.name,level:d.level||0,slot:d.slot,ok:ok})}catch(e){}})()}
function hear_incoming(d){if(!d||!d.name)return;gift_ttl[d.id||d.name]={name:d.name,expire_ms:Date.now()+120000}}
function class_ok(it){var g=G.items[it.name]||{},w=g.wtype,c=character.ctype;if(!w)return true;if(c==="warrior")return["sword","short_sword","wblade","basher","axe","mace","spear"].indexOf(w)>=0;if(c==="mage"||c==="priest")return["staff","great_staff","wand"].indexOf(w)>=0;return false}
function candidate_slots(it){var g=G.items[it.name]||{},t=g.type;if(!class_ok(it))return[];if(t==="ring")return["ring1","ring2"];if(t==="amulet")return["amulet"];if(t==="belt")return["belt"];if(t==="helmet")return["helmet"];if(t==="chest")return["chest"];if(t==="pants")return["pants"];if(t==="shoes")return["shoes"];if(t==="gloves")return["gloves"];if(t==="cape")return["cape"];if(t==="weapon"||g.wtype)return["mainhand"];if(t==="shield"||t==="source"||t==="quiver"||t==="misc_offhand")return["offhand"];return[]}
function score(it,slot){if(!it)return 0;var g=G.items[it.name]||{},p=typeof item_properties==="function"?item_properties(it):null,ctype=character.ctype,prim;if(p){if(g.type==="weapon"||g.wtype)return p.attack||0;if(g.type==="ring"||g.type==="amulet"||g.type==="belt"){prim=ctype==="mage"?p.int:ctype==="priest"?p.vit:p.str;return(prim||p.str||p.int||p.vit||1)+0.01*(it.level||0)}return(p.armor||0)+(p.resistance||0)+0.02*(p.hp||0)}return((g.attack||g.armor||1)+(g.resistance||0))*(1+0.08*(it.level||0))}
function pending_better(it){var targets=candidate_slots(it),s,worn,i;for(i=0;i<targets.length;i++){s=targets[i];worn=character.slots[s];if(score(it,s)>(worn?score(worn,s):0))return true}return false}
function is_keep(it){var id;if(!it)return true;if(is_pot(it)||it.name==="stand0"||it.name==="tracker"||it.l)return true;if(/^scroll\d$/.test(it.name)||/^cscroll\d$/.test(it.name))return true;for(id in gift_ttl)if(gift_ttl[id]&&gift_ttl[id].name===it.name&&Date.now()<gift_ttl[id].expire_ms)return true;return!!pending_better(it)}
async function equip_pending(){var i,it,targets,best,s,worn,sw,j;for(i=0;i<character.items.length;i++){it=character.items[i];if(!it)continue;targets=candidate_slots(it);best=null;for(j=0;j<targets.length;j++){s=targets[j];worn=character.slots[s];sw=worn?score(worn,s):0;if(score(it,s)>sw&&(!best||sw<best.sw))best={slot:s,sw:sw}}if(best){try{await equip(i,best.slot)}catch(e){}for(s in gift_ttl)if(gift_ttl[s]&&gift_ttl[s].name===it.name)delete gift_ttl[s]}}}
async function bank_dump(){if(character.map!=="bank")return;await equip_pending();for(var i=0,it;i<character.items.length;i++)if((it=character.items[i])&&!is_keep(it))try{await bank_store(i)}catch(e){}}
function member(n){return n===character.name?character:((get_party()||{})[n]||get_player(n))}
function psay(msg,force){if(!msg||(!force&&mssince(last_psay)<PSAY_MS))return false;last_psay=new Date();try{party_say(msg)}catch(e){}return true}
function desired(){var lvl=99,hp=character.max_hp,i,j,d,pickm,p,cap,n,s;if(farm_ovr&&G.monsters[farm_ovr])return farm_ovr;bump(character.name,character.level,character.max_hp);for(i=0;i<PARTY.length;i++){n=PARTY[i];p=member(n);if(p&&!p.rip&&p.level>=1)bump(n,p.level,p.max_hp||0);s=seen[n];if(s&&s.l&&s.l<lvl){lvl=s.l;hp=s.h||hp}}if(lvl===99)lvl=character.level;lvl=Math.min(lvl,90);pickm=LADDER[0][1];cap=Math.max(8,Math.floor(hp*MAX_ATTACK_RATIO));for(i=0;i<LADDER.length;i++)if(lvl>=LADDER[i][0])pickm=LADDER[i][1];if(G.monsters[pickm]&&G.monsters[pickm].attack>cap){for(j=LADDER.length-1;j>=0;j--){d=G.monsters[LADDER[j][1]];if(d&&d.attack<=cap&&lvl>=LADDER[j][0])return LADDER[j][1]}return"goo"}return pickm}
function restock_cost(){var hp=pot("hp"),mp=pot("mp");return Math.max(0,POTION_TARGET-quantity(hp))*price(hp)+Math.max(0,POTION_TARGET-quantity(mp))*price(mp)}
function low_pots(){return quantity(pot("hp"))<POTION_MIN||quantity(pot("mp"))<POTION_MIN}
function needs_pots(){var c=restock_cost();return low_pots()&&c>0&&character.gold>=c}
function needs_vendor(){return character.esize===0||needs_pots()}
function find_merch(){var m=get_player(MERCHANT),id,p;if(m)return m;for(id in parent.entities){p=parent.entities[id];if(p&&p.type==="character"&&p.name&&(""+p.name).toLowerCase()===MERCHANT.toLowerCase())return p}return null}
async function offload(){var m=find_merch(),g;if(mssince(last_gold)<2500||!m||m.rip||character.bank||(g=Math.floor(character.gold-1000))<=0||parent.distance(character,m)>320)return;last_gold=new Date();try{await send_gold(m.name,g)}catch(e){last_gold=new Date(0);game_log("Gold fail:"+((e&&e.reason)||e))}}
async function hang_hold(){if(!(character.bank||character.map==="bank"))return offload();if(!smart.moving)try{await smart_move({to:"potions"})}catch(e){}}
function use_pots(){if(safeties&&mssince(last_potion)<min(200,character.ping*3)||is_on_cooldown("use_hp"))return;var skill=character.hp/character.max_hp<0.5?"use_hp":character.mp/character.max_mp<0.5?"use_mp":null;if(skill){last_potion=new Date();use_skill(skill)}}
function ding(){if(character.level<=last_lv)return;last_lv=character.level;psay(hooks&&hooks.ding_line||"Ding!")}
function on_party_invite(name){if(in_arr(name,PARTY))accept_party_invite(name)}
function invite_party(){if(!(hooks&&hooks.do_invite)||!is_lead||mssince(last_invite)<5000)return;var p=get_party()||{},i,sent=false;for(i=0;i<PARTY.length;i++)if(PARTY[i]!==character.name&&!p[PARTY[i]]){send_party_invite(PARTY[i]);sent=true}if(sent)last_invite=new Date()}
async function buy_pots(){var hp=pot("hp"),mp=pot("mp"),hb=Math.max(0,POTION_TARGET-quantity(hp)),mb=Math.max(0,POTION_TARGET-quantity(mp));if((!hb&&!mb)||character.gold<hb*price(hp)+mb*price(mp))return;if(hb)try{await buy(hp,hb)}catch(e){}if(mb)try{await buy(mp,mb)}catch(e){}}
async function restock(to){if(!in_arr(character.map,["main","halloween","winterland","winter_inn","winter_cave","bank"])){use("town");await sleep(2000)}if(to!=="upgrade"){if(hold)psay("Hold: banking",1);if(smart.moving)return;if((await smart_move({to:"bank"})||{}).failed)return;await bank_dump();await sleep(400)}if(smart.moving)return;if((await smart_move({to:to||"potions"})||{}).failed)return;if(to!=="upgrade"){if(hold)psay("Hold: buying pots",1);await buy_pots()}}
function set_hold(v,announce){var was=hold;hold=!!v;hold_done=false;ls(hold?1:0);form_anchor=null;form_slot=null;try{stop("smart")}catch(e){}if(hold)go_s(HOME);else go_s(FARM);if(announce){if(hold&&!was)psay("Hold: restocking",1);else if(!hold&&was)psay("Resuming",1)}broadcast_state(true)}
function set_hunt(k,announce){try{stop("smart")}catch(e){}if(!k){farm_ovr=farm=null;if(announce)psay("Back to the grind",1)}else if(G.monsters[k]){farm_ovr=farm=k;if(announce)psay("Let's kill "+k+"!",1)}broadcast_state(true)}
function apply_cmd(cmd,announce){if(!cmd)return;if(cmd.type==="hold")set_hold(1,announce);else if(cmd.type==="resume")set_hold(0,announce);else if(cmd.type==="grind")set_hunt("",announce);else if(cmd.type==="hunt"&&cmd.mtype)set_hunt(cmd.mtype,announce)}
function lead_ent(){return get_player(LEADER)||(get_party()||{})[LEADER]||null}
function leader_ok(){var L=lead_ent();return!!(L&&!L.rip&&(L.map||L.real_x!=null||L.x!=null))}
function formation_pos(lead,form,angle){var dx=form.dx||0,dy=form.dy||0,x=lead.real_x!=null?lead.real_x:lead.x,y=lead.real_y!=null?lead.real_y:lead.y,c,s;if(form.face&&angle!=null&&!isNaN(angle)){c=Math.cos(angle);s=Math.sin(angle);return{map:lead.map,x:x+dx*c-dy*s,y:y+dx*s+dy*c}}return{map:lead.map,x:x+dx,y:y+dy}}
async function follow_formation(){var L,ang,lx,ly,slot,d,dx,dy,ad;if(hold||character.rip||smart.moving||!hooks||!hooks.form)return false;if(!leader_ok()){form_anchor=null;form_slot=null;return false}L=lead_ent();lx=L.real_x!=null?L.real_x:L.x;ly=L.real_y!=null?L.real_y:L.y;if(L.angle!=null)last_lead_angle=L.angle;ang=L.angle!=null?L.angle:last_lead_angle;ad=!form_anchor||form_anchor.map!==L.map?1e9:Math.sqrt((lx-form_anchor.x)*(lx-form_anchor.x)+(ly-form_anchor.y)*(ly-form_anchor.y));if(!form_slot||ad>FORM_REANCHOR){form_slot=formation_pos({map:L.map,real_x:lx,real_y:ly,x:lx,y:ly},hooks.form,ang);form_anchor={map:L.map,x:lx,y:ly}}slot=form_slot;dx=character.real_x-slot.x;dy=character.real_y-slot.y;d=character.map!==slot.map?1e9:Math.sqrt(dx*dx+dy*dy);if(character.map===slot.map&&d<=FORM_NEAR)return true;if(character.map===slot.map&&d<=FORM_SMART){if(d>FORM_FAR)move(slot.x,slot.y);return true}try{await smart_move({map:slot.map,x:slot.x,y:slot.y})}catch(e){game_log("form:"+((e&&e.message)||e))}return true}
function farm_near(mtype){var mons=(G.maps&&G.maps[character.map]&&G.maps[character.map].monsters)||[],i,m,b,x0,x1,y0,y1,cx,cy,dx,dy;for(i=0;i<mons.length;i++){m=mons[i];if(!m||m.type!==mtype)continue;if(m.boundary){b=m.boundary;x0=Math.min(b[0],b[2]);x1=Math.max(b[0],b[2]);y0=Math.min(b[1],b[3]);y1=Math.max(b[1],b[3]);cx=Math.min(Math.max(character.real_x,x0),x1);cy=Math.min(Math.max(character.real_y,y0),y1);dx=character.real_x-cx;dy=character.real_y-cy;if(Math.sqrt(dx*dx+dy*dy)<=FARM_NEAR)return true}else if(m.position){dx=character.real_x-m.position[0];dy=character.real_y-m.position[1];if(Math.sqrt(dx*dx+dy*dy)<=(m.radius||180)+FARM_NEAR)return true}}return false}
async function go_farm(mtype){if(!mtype||smart.moving||mssince(last_farm_go)<FARM_GO_MS)return;last_farm_go=new Date();set_message("Off to "+mtype);try{if(!farm_near(mtype)){use("town");await sleep(2000)}if(smart.moving)return;if((await smart_move({to:mtype})||{}).failed){use("town");await sleep(2000);if(!smart.moving)await smart_move({to:mtype})}}catch(e){game_log("go_farm:"+((e&&e.message)||e))}}
function farmable(t){return t&&!t.dead&&t.mtype&&t.mtype.indexOf("target")<0&&!(G.monsters[t.mtype]||{}).unlist}
function ready(s){var d=G.skills[s]||{};return can_use(s)&&character.mp>=(d.mp||0)&&(!d.level||character.level>=d.level)}
function broadcast_state(force){var f=farm_ovr||farm||"-",msg;if(!is_lead)return;msg="~s h="+(hold?1:0)+" f="+f;if(!force&&(mssince(last_s)<STATE_MS||msg===last_s_msg))return;if(!psay(msg))return;last_s=new Date();last_s_msg=msg}
function parse_status(m){var out={},parts=(""+m).replace(/^~s\s*/i,"").split(/\s+/),i,kv;for(i=0;i<parts.length;i++){kv=parts[i].split("=");if(kv.length===2)out[kv[0]]=kv[1]}return out}
function parse_cmd(raw){var m=(""+(raw||"")).trim(),low=m.toLowerCase(),k;if(low==="!hold")return{type:"hold"};if(low==="!resume")return{type:"resume"};if(low==="!grind")return{type:"grind"};if(low.indexOf("!hunt ")===0){k=low.slice(6).replace(/[^a-z0-9_]/g,"");return k?{type:"hunt",mtype:k}:null}if(low.indexOf("let's kill ")===0||low.indexOf("lets kill ")===0){k=low.replace(/^let'?s kill /,"").replace(/!+$/,"").replace(/[^a-z0-9_]/g,"");return k?{type:"hunt",mtype:k}:null}if(low.indexOf("back to the grind")>=0)return{type:"grind"};return null}
function slot_ad(s){var it=character.slots[s];return it?it.name+"@"+(it.level||0):"-"}
function send_gear_ad(){var slots={mainhand:slot_ad("mainhand"),offhand:slot_ad("offhand"),helmet:slot_ad("helmet"),chest:slot_ad("chest"),pants:slot_ad("pants"),shoes:slot_ad("shoes"),gloves:slot_ad("gloves"),cape:slot_ad("cape"),belt:slot_ad("belt"),amulet:slot_ad("amulet"),ring1:slot_ad("ring1"),ring2:slot_ad("ring2")};try{send_cm(MERCHANT,{gear_ad:1,name:character.name,esize:character.esize,slots:slots})}catch(e){}last_gear_ad=new Date()}
function hear_cmd(m){if(!m)return;var from=(""+(m.name||m.from||"")).toLowerCase(),d=m.message!=null?m.message:m.data,v=null,h=null;if(from!==MERCHANT.toLowerCase())return;if(typeof d==="string"){if(d.indexOf("hold:1")>=0)v=1;else if(d.indexOf("hold:0")>=0)v=0;else if(d.indexOf("hunt:")===0)h=d.slice(5);else if(/^grind/i.test(d))h="";else try{d=JSON.parse(d)}catch(e){return}}if(typeof d==="object"&&d){if(d.gear_incoming){hear_incoming(d);return}if(d.gear_offer){handle_gear_offer(d);return}if(d.gear_busy)return;if(d.hold!=null)v=d.hold;if(d.hunt!=null)h=d.hunt;if(d.grind)h=""}if(h!=null&&is_lead){set_hunt(h===""?"":(""+h).toLowerCase().replace(/[^a-z0-9_]/g,""),true);return}if(v==1)set_hold(1,true);else if(v==0)set_hold(0,true)}
function hear(d){if(!d||d.message==null)return;var cmd=parse_cmd(d.message),m,from=d.from;if(cmd){apply_cmd(cmd,!from||from===character.name);return}m=(""+d.message).toLowerCase();if(m.indexOf("~s")===0){parse_status(d.message);return}if(!from||from===character.name)return;if(m.indexOf("ding")>=0)psay(pick(["Gratz!","Yes!","Proud of you."]));if(!in_arr(from,PARTY))return;if(m.indexOf("potion")>=0){psay(pick(["Ok!","On my way!","Coming!"]));rally="potions"}else if(m.indexOf("upgrade")>=0){psay(pick(["Ok!","On my way!","Coming!"]));rally="upgrade"}}
function busy_watch(){if(busy&&busy_since&&Date.now()-busy_since>BUSY_MS){busy=false;busy_since=0;try{stop("smart")}catch(e){}game_log("busy timeout")}}
function smart_watch(){if(!smart.moving){last_xy=null;return}var k=character.real_x+","+character.real_y;if(last_xy!==k){last_xy=k;last_xy_t=Date.now();return}if(Date.now()-last_xy_t>SMART_STUCK_MS){try{stop("smart")}catch(e){}game_log("smart stuck");last_xy=null}}
function handle_death(){psay(pick(["Ow.","Down!","Not today."]));setTimeout(respawn,15000);return true}
async function logistics(){if(busy||character.rip)return;busy=true;busy_since=Date.now();try{if(character.map==="jail"){psay("Jail. Ugh.");await leave();busy=false;busy_since=0;return}offload();if(hold){if(go_s(HOME)){}else if(!hold_done){set_message("Hold");await restock("potions");if(hold){hold_done=true;psay("Hold: ready",1);await hang_hold()}}else{set_message("Hold");await hang_hold()}}else if(go_s(FARM)){}else{if(character.hp<character.max_hp*0.2&&quantity(pot("hp"))===0)rally="potions";if(needs_vendor()||rally){if(needs_vendor()&&mssince(last_pots_say)>20000){if(psay("I need some potions!"))last_pots_say=new Date()}set_message("Vendor");await restock(rally==="upgrade"?"upgrade":"potions");rally=false}else{farm=desired();if(is_lead){if(!get_nearest_monster({type:farm,max_att:farm_ovr?1e9:att_cap()})&&!smart.moving)await go_farm(farm)}else if(leader_ok()){set_message("Form");await follow_formation()}else if(!smart.moving)await go_farm(farm)}}}catch(e){game_log("logistics fail:"+((e&&(e.message||e.reason))||e))}busy=false;busy_since=0}
function boot_fighter(h){hooks=h||{};try{performance_trick()}catch(e){}character.on("partym",hear);character.on("cm",hear_cmd);character.on("pm",hear_cmd);setInterval(function(){ding();use_pots();loot();offload();invite_party();busy_watch();smart_watch();broadcast_state(false);if(hold||mssince(last_gear_ad)>GEAR_AD_MS)send_gear_ad();if(hold&&hold_done&&!smart.moving)hang_hold();if(hold&&!hold_done&&!busy&&!character.rip)logistics();if(character.rip||hold||!ATTACK_MODE||busy||smart.moving)return;if(hooks.pre_combat&&hooks.pre_combat())return;if(hooks.combat)hooks.combat(farm||desired())},250);setInterval(logistics,2500)}
