var ATTACK_MODE=true,POTION_TARGET=500,POTION_MIN=40,MAX_ATTACK_RATIO=0.24;
var LEADER="Jazwyn",TANK="Jazwyn",MERCHANT="Puppygirl",PARTY=["Jazwyn","Sarene","Zarook"];
var LADDER=[[1,"goo"],[4,"bee"],[8,"crab"],[12,"snake"],[16,"armadillo"],[20,"arcticbee"],[24,"porcupine"],[28,"croc"],[30,"tortoise"],[32,"bat"],[50,"gscorpion"],[58,"wolfie"],[66,"wolf"]];
var FARM_BAN=["spider","scorpion","bigbird"];
var HOME=["US","II"],FARM=["US","III"],FORM_NEAR=18,FORM_FAR=40,FORM_SMART=220,FORM_REANCHOR=70,BUSY_MS=60000,SMART_STUCK_MS=20000,PSAY_MS=2500,FARM_GO_MS=10000,FARM_NEAR=60,STATE_MS=20000,GEAR_AD_MS=20000,CM_GAP_MS=700,REQ_COOLDOWN_MS=60000,BEACON_MS=8000,ACK_MS=20000,PENDING_MS=480000;
var busy=false,busy_since=0,farm=null,farm_ovr=null,last_lv=character.level,is_lead=character.name===LEADER,farm_walking=false;
var HK="hold_"+character.name,rally=false,hold_done=false,hooks=null,last_lead_angle=null,form_anchor=null,form_slot=null,last_s=new Date(0),last_s_msg="",last_psay=new Date(0),last_farm_go=new Date(0),last_xy=null,last_xy_t=0,gift_ttl={},last_gear_ad=new Date(0),last_cm_t=0,dlv_pending=null,last_req_at=0,last_beacon=0,lead_blind_since=0,last_gos_wait=0,LIVE_TEST=0,live_dlv_done=0,live_dump_done=0,LIVE_DUMP_TO="Sarene";
function ms(t){return Date.now()-(t instanceof Date?t.getTime():+t||0)}
if(typeof min!=="function")min=Math.min;if(typeof last_potion==="undefined")var last_potion=new Date(0);
function ls(v){try{if(v==null)return localStorage.getItem(HK)==="1";localStorage.setItem(HK,v?"1":"0")}catch(e){return false}}
var hold=!!ls(),last_pots_say=new Date(0),last_gold=new Date(0),last_invite=new Date(0),seen={};
function go_s(s){if(!parent.server_region||!parent.server_identifier){if(ms(last_gos_wait)>10000){game_log("go_s:wait");last_gos_wait=Date.now()}return false}if(parent.server_region===s[0]&&parent.server_identifier===s[1])return false;game_log("go_s:"+s[0]+"/"+s[1]+" from "+parent.server_region+"/"+parent.server_identifier);try{change_server(s[0],s[1])}catch(e){}return true}
function pot(kind){return kind==="hp"?(character.level>=30?"hpot1":"hpot0"):(character.level>=30?"mpot1":"mpot0")}
function bump(n,lv,hp){var s=seen[n]||(seen[n]={l:0,h:0});if(lv>s.l)s.l=lv;if(hp>s.h)s.h=hp;return s}
function att_cap(){return Math.max(8,Math.floor(bump(character.name,character.level,character.max_hp).h*MAX_ATTACK_RATIO))}
function price(name){return(G.items[name]&&G.items[name].g)||20}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function is_pot(it){return it&&(it.name.indexOf("hpot")===0||it.name.indexOf("mpot")===0)}
function handle_gear_offer(d){var i,it,ok=0,id,slot;if(!d||!d.name)return;id=d.id||d.name;gift_ttl[id]={name:d.name,expire_ms:Date.now()+120000};(async function(){await equip_pending();for(i=0;i<character.items.length;i++){it=character.items[i];if(it&&it.name===d.name&&(it.level||0)===(d.level||0)){try{await equip(i,d.slot||undefined)}catch(e){}break}}await equip_pending();slot=d.slot;if(slot&&character.slots[slot]&&character.slots[slot].name===d.name&&(character.slots[slot].level||0)===(d.level||0))ok=1;try{send_cm(MERCHANT,{gear_got:1,id:d.id,name:d.name,level:d.level||0,slot:d.slot,ok:ok})}catch(e){}})()}
function hear_incoming(d){if(!d||!d.name)return;gift_ttl[d.id||d.name]={name:d.name,expire_ms:Date.now()+120000}}
function class_ok(it){var g=G.items[it.name]||{},w=g.wtype,c=character.ctype;if(!w)return true;if(c==="warrior")return["sword","short_sword","wblade","basher","axe","mace","spear"].indexOf(w)>=0;if(c==="mage"||c==="priest")return["staff","great_staff","wand"].indexOf(w)>=0;return false}
function candidate_slots(it){var g=G.items[it.name]||{},t=g.type;if(!class_ok(it))return[];if(t==="ring")return["ring1","ring2"];if(t==="amulet")return["amulet"];if(t==="belt")return["belt"];if(t==="helmet")return["helmet"];if(t==="chest")return["chest"];if(t==="pants")return["pants"];if(t==="shoes")return["shoes"];if(t==="gloves")return["gloves"];if(t==="cape")return["cape"];if(t==="weapon"||g.wtype)return["mainhand"];if(t==="shield"||t==="source"||t==="quiver"||t==="misc_offhand")return["offhand"];return[]}
function score(it,slot){if(!it)return 0;var g=G.items[it.name]||{},p=typeof item_properties==="function"?item_properties(it):null,ctype=character.ctype,prim,dr;if(p){if(g.type==="weapon"||g.wtype)return p.attack||0;if(g.type==="ring"||g.type==="amulet"||g.type==="belt"){prim=ctype==="mage"?p.int:ctype==="priest"?p.vit:p.str;return(prim||p.str||p.int||p.vit||1)+0.01*(it.level||0)}dr=p.dreturn||0;return(p.armor||0)+(p.resistance||0)+0.02*(p.hp||0)+40*dr}dr=g.dreturn||0;return((g.attack||g.armor||1)+(g.resistance||0)+40*dr)*(1+0.08*(it.level||0))}
function pending_better(it){var targets=candidate_slots(it),s,worn,i;for(i=0;i<targets.length;i++){s=targets[i];worn=character.slots[s];if(score(it,s)>(worn?score(worn,s):0))return true}return false}
function is_keep(it){var id;if(!it)return true;if(is_pot(it)||it.name==="stand0"||it.name==="tracker"||it.l)return true;if(/^scroll\d$/.test(it.name)||/^cscroll\d$/.test(it.name))return true;for(id in gift_ttl)if(gift_ttl[id]&&gift_ttl[id].name===it.name&&Date.now()<gift_ttl[id].expire_ms)return true;return!!pending_better(it)}
async function equip_pending(){var i,it,targets,best,s,worn,sw,j;for(i=0;i<character.items.length;i++){it=character.items[i];if(!it)continue;targets=candidate_slots(it);best=null;for(j=0;j<targets.length;j++){s=targets[j];worn=character.slots[s];sw=worn?score(worn,s):0;if(score(it,s)>sw&&(!best||sw<best.sw))best={slot:s,sw:sw}}if(best){try{await equip(i,best.slot)}catch(e){}for(s in gift_ttl)if(gift_ttl[s]&&gift_ttl[s].name===it.name)delete gift_ttl[s]}}}
async function bank_dump(){if(character.map!=="bank")return;await equip_pending();for(var i=0,it;i<character.items.length;i++)if((it=character.items[i])&&!is_keep(it))try{await bank_store(i)}catch(e){}}
function member(n){return n===character.name?character:((get_party()||{})[n]||get_player(n))}
function psay(msg,force){if(!msg||(!force&&ms(last_psay)<PSAY_MS))return false;last_psay=new Date();try{party_say(msg)}catch(e){}return true}
function desired(){var lvl=99,hp=character.max_hp,i,j,d,pickm,p,cap,n,s;if(farm_ovr&&G.monsters[farm_ovr]&&FARM_BAN.indexOf(farm_ovr)<0)return farm_ovr;bump(character.name,character.level,character.max_hp);for(i=0;i<PARTY.length;i++){n=PARTY[i];p=member(n);if(p&&!p.rip&&p.level>=1)bump(n,p.level,p.max_hp||0);s=seen[n];if(s&&s.l&&s.l<lvl){lvl=s.l;hp=s.h||hp}}if(lvl===99)lvl=character.level;lvl=Math.min(lvl,90);pickm=LADDER[0][1];cap=Math.max(8,Math.floor(hp*MAX_ATTACK_RATIO));for(i=0;i<LADDER.length;i++)if(lvl>=LADDER[i][0])pickm=LADDER[i][1];if(G.monsters[pickm]&&G.monsters[pickm].attack>cap){for(j=LADDER.length-1;j>=0;j--){d=G.monsters[LADDER[j][1]];if(d&&d.attack<=cap&&lvl>=LADDER[j][0])return LADDER[j][1]}return"goo"}return pickm}
function restock_cost(){var hp=pot("hp"),mp=pot("mp");return Math.max(0,POTION_TARGET-quantity(hp))*price(hp)+Math.max(0,POTION_TARGET-quantity(mp))*price(mp)}
function low_pots(){var min=is_lead?Math.max(POTION_MIN||40,150):(POTION_MIN||40);return quantity(pot("hp"))<min||quantity(pot("mp"))<min}
function dry_pots(){return quantity(pot("hp"))===0||quantity(pot("mp"))===0}
function needs_pots(){return low_pots()}
function needs_vendor(){return character.esize===0}
async function cm_send(to,msg){var w=(CM_GAP_MS||700)-ms(new Date(last_cm_t));if(w>0)await sleep(w);last_cm_t=Date.now();try{await send_cm(to,msg)}catch(e){game_log("cm fail:"+((e&&e.reason)||e))}}
function pot_need_items(){var hp=pot("hp"),mp=pot("mp"),items=[],hb=Math.min(200,Math.max(0,POTION_TARGET-quantity(hp))),mb=Math.min(200,Math.max(0,POTION_TARGET-quantity(mp)));if(LIVE_TEST&&!live_dlv_done){hb=Math.min(hb||40,40);mb=Math.min(mb||40,40)}if(hb)items.push({name:hp,q:hb});if(mb)items.push({name:mp,q:mb});return items}
function dlv_clear(why){if(dlv_pending)game_log("dlv:clear "+dlv_pending.id+" "+(why||""));dlv_pending=null}
async function cancel_dlv(why){var id;if(!dlv_pending)return;id=dlv_pending.id;await cm_send(MERCHANT,{v:1,dlv_cancel:1,id:id,reason:why||"town"});game_log("dlv:cancel "+id+" "+(why||"town"));dlv_clear(why||"cancel")}
async function live_dump_pots(){var name=LIVE_DUMP_TO||"Sarene",p=get_player(name),id,e,px,py,dist,i,it,sent=0,party;if(!is_lead){live_dump_done=1;return}if(!p){for(id in parent.entities){e=parent.entities[id];if(e&&e.type==="character"&&e.name===name){p=e;break}} }if(!p){party=(get_party()||{})[name];if(party)p=party}if(!p){game_log("LIVE_DUMP wait no "+name);return}px=p.real_x!=null?p.real_x:p.x;py=p.real_y!=null?p.real_y:p.y;if(p.map&&character.map&&p.map!==character.map){game_log("LIVE_DUMP wait map "+p.map);return}dist=Math.sqrt(Math.pow((character.real_x||0)-px,2)+Math.pow((character.real_y||0)-py,2));if(!(dist<=280)||!get_player(name)){game_log("LIVE_DUMP approach "+Math.floor(dist));if(!smart.moving)try{await smart_move({map:character.map,x:px,y:py})}catch(e0){}return}for(i=0;i<character.items.length;i++){it=character.items[i];if(!it||!is_pot(it))continue;try{await send_item(name,i,it.q||1);sent++;game_log("LIVE_DUMP send "+it.name+" "+(it.q||1));await sleep(200)}catch(e1){game_log("LIVE_DUMP fail "+((e1&&e1.reason)||e1));return}}live_dump_done=1;last_req_at=0;game_log("LIVE_DUMP_OK hp="+quantity(pot("hp"))+" mp="+quantity(pot("mp"))+" sent="+sent)}
async function request_pots(){var items,id,qsum="",srv,pk,age,cd;if(dlv_pending){age=Date.now()-dlv_pending.t0;if(age>(dlv_pending.acked?(PENDING_MS||240000):(ACK_MS||20000))){last_req_at=0;dlv_clear(dlv_pending.acked?"pending_timeout":"ack_timeout")}else return}cd=(LIVE_TEST&&live_dump_done&&!live_dlv_done)?2000:(REQ_COOLDOWN_MS||60000);if(ms(new Date(last_req_at))<cd)return;if((character.esize||0)<1){game_log("dlv:skip pots no_space");return}items=pot_need_items();if(!items.length)return;id="p"+Date.now()+"_"+character.name.slice(0,3);pk=farm||desired()||null;dlv_pending={id:id,kind:"pots",t0:Date.now(),acked:0};items.forEach(function(it){qsum+=(qsum?"+":"")+it.name+":"+it.q});srv=(parent.server_region&&parent.server_identifier)?[parent.server_region,parent.server_identifier]:FARM;game_log("dlv:req id="+id+" kind=pots q="+qsum+" farm="+(pk||"-")+" @"+srv[0]+"/"+srv[1]+" "+character.map+" "+Math.floor(character.real_x)+","+Math.floor(character.real_y));await cm_send(MERCHANT,{v:1,dlv_req:1,id:id,kind:"pots",items:items,map:character.map,x:character.real_x,y:character.real_y,server:srv,esize:character.esize,farm:pk})}
async function dlv_beacon(){if(!dlv_pending||ms(new Date(last_beacon))<(BEACON_MS||8000))return;last_beacon=Date.now();await cm_send(MERCHANT,{v:1,dlv_loc:1,dlv_ping:1,id:dlv_pending.id,map:character.map,x:character.real_x,y:character.real_y,server:(parent.server_region&&parent.server_identifier)?[parent.server_region,parent.server_identifier]:FARM,farm:farm||desired()||null})}
function hear_dlv(d){if(!d)return;if(d.dlv_need_q){(async function(){var items=pot_need_items();game_log("dlv:need_q id="+d.id+" n="+items.length);await cm_send(MERCHANT,{v:1,dlv_need:1,id:d.id,items:items,map:character.map,x:character.real_x,y:character.real_y,esize:character.esize,server:(parent.server_region&&parent.server_identifier)?[parent.server_region,parent.server_identifier]:FARM})}());return}if(d.dlv_loot_q){(async function(){var n;game_log("dlv:loot_q id="+(d.id||"-"));n=await toss_loot();game_log("dlv:toss n="+n);await cm_send(MERCHANT,{v:1,dlv_loot_done:1,id:d.id||null,n:n})}());return}if(d.dlv_status){if(d.phase==="none"){if(dlv_pending&&(!d.id||d.id===dlv_pending.id)){last_req_at=0;dlv_clear("none")}game_log("dlv:status none");return}if(dlv_pending&&(!d.id||d.id===dlv_pending.id)){dlv_pending.phase=d.phase;dlv_pending.status_msg=d.msg;if(d.phase&&d.phase!=="none")dlv_pending.t0=Date.now()}game_log("dlv:status "+(d.msg||d.phase||"?")+(d.map?" @"+d.map+" "+(d.x!=null?d.x:"?")+","+(d.y!=null?d.y:"?"):""));try{set_message(String(d.msg||"On my way").slice(0,24))}catch(e0){}return}if(d.dlv_meet){game_log("dlv:meet ignored (stay farm)");return}if(d.dlv_sent&&(!dlv_pending||!d.id||d.id===dlv_pending.id||d.party)){(async function(){var ok=1,i,it,have={};for(i=0;i<(d.items||[]).length;i++){it=d.items[i];have[it.name]=quantity(it.name);if(quantity(it.name)<(it.q||0))ok=0}game_log("dlv:got id="+d.id+" ok="+ok);if(LIVE_TEST&&ok){live_dlv_done=1;game_log("LIVE_DLV_OK id="+d.id);game_log("LIVE_RESTOCK_OK hp="+quantity(pot("hp"))+" mp="+quantity(pot("mp")))}await cm_send(MERCHANT,{v:1,dlv_got:1,id:d.id,ok:ok,have:have})}());return}if(!dlv_pending||(d.id&&d.id!==dlv_pending.id))return;if(d.dlv_ack){game_log("dlv:ack id="+d.id+" ok="+d.ok);if(d.ok)dlv_pending.acked=1;else{last_req_at=Date.now();dlv_clear(d.reason||"rej")}return}if(d.dlv_here){if(dlv_pending)dlv_pending.t0=Date.now();game_log("dlv:here id="+d.id);return}if(d.dlv_done||d.dlv_cancel){last_req_at=Date.now();if(d.ok){live_dlv_done=1;game_log("LIVE_DLV_OK id="+d.id);game_log("LIVE_RESTOCK_OK hp="+quantity(pot("hp"))+" mp="+quantity(pot("mp")))}game_log("dlv:done id="+d.id+" ok="+(d.ok!=null?d.ok:0));dlv_clear("done")}}
async function toss_loot(){var m=null,i,it,n=0,d,t0=Date.now();if(character.bank){game_log("toss skip bank");return 0}while(Date.now()-t0<1500){m=find_merch();if(m&&!m.rip)break;await sleep(250)}if(!m||m.rip){game_log("toss skip no_merch");return 0}d=parent.distance(character,m);if(!(d<=400)){game_log("toss skip dist "+Math.floor(d));return 0}for(i=0;i<character.items.length&&n<12;i++){it=character.items[i];if(!it||is_keep(it))continue;try{await send_item(m.name,i,it.q||1);n++;game_log("toss "+it.name)}catch(e){game_log("toss fail:"+((e&&e.reason)||e));break}}return n}
function find_merch(){var m=get_player(MERCHANT),id,p;if(m)return m;for(id in parent.entities){p=parent.entities[id];if(p&&p.type==="character"&&p.name&&(""+p.name).toLowerCase()===MERCHANT.toLowerCase())return p}return null}
async function offload(){var m=find_merch(),g;if(ms(last_gold)<2500||!m||m.rip||character.bank||(g=Math.floor(character.gold-1000))<=0||parent.distance(character,m)>320)return;last_gold=new Date();try{await send_gold(m.name,g)}catch(e){last_gold=new Date(0);game_log("Gold fail:"+((e&&e.reason)||e))}await toss_loot()}
async function hang_hold(){if(!(character.bank||character.map==="bank"))return offload();if(!smart.moving)try{await smart_move({map:"main",x:56,y:-122})}catch(e){}}
function use_pots(){if(safeties&&ms(last_potion)<min(200,character.ping*3)||is_on_cooldown("use_hp"))return;var skill=character.hp/character.max_hp<0.5?"use_hp":character.mp/character.max_mp<0.5?"use_mp":null;if(skill){last_potion=new Date();use_skill(skill)}}
function ding(){if(character.level<=last_lv)return;last_lv=character.level;psay(hooks&&hooks.ding_line||"Ding!")}
function on_party_invite(name){if(in_arr(name,PARTY)){accept_party_invite(name);game_log("party:accept "+name)}}
function invite_party(){var p=get_party()||{},i,sent=false;if(!(hooks&&hooks.do_invite)||!is_lead||ms(last_invite)<5000)return;for(i=0;i<PARTY.length;i++)if(PARTY[i]!==character.name&&!p[PARTY[i]]){send_party_invite(PARTY[i]);sent=true}if(sent)last_invite=new Date()}
function party_with_lead(){return!!(is_lead||(get_party()||{})[LEADER])}
async function buy_pots(){var hp=pot("hp"),mp=pot("mp"),hb=Math.max(0,POTION_TARGET-quantity(hp)),mb=Math.max(0,POTION_TARGET-quantity(mp)),cost,n,ph=price(hp),pm=price(mp),g=character.gold;if(!hb&&!mb)return;if(!(ph>0&&pm>0))return;if(g<ph&&g<pm){game_log("buy_pots no gold");return}n=Math.min(hb,Math.floor(g/ph));if(n>0){try{await buy(hp,n);g=character.gold}catch(e){}}n=Math.min(mb,Math.floor(g/pm));if(n>0)try{await buy(mp,n)}catch(e2){}}
async function buy_pots_here(){var r;if(character.map!=="main"&&character.map!=="bank"){use("town");await sleep(2000)}if(character.map==="bank"){try{await smart_move({map:"main",x:56,y:-122})}catch(e0){try{use("town");await sleep(1500)}catch(e1){}}}else{try{r=await smart_move({map:"main",x:56,y:-122})}catch(e2){r={failed:1}}if(r&&r.failed)try{await smart_move({map:"main",x:40,y:-120})}catch(e3){}}await buy_pots()}
async function restock(to){var r,dest;if(!in_arr(character.map,["main","halloween","winterland","winter_inn","winter_cave","bank"])){use("town");await sleep(2000)}if(to!=="upgrade"){if(hold&&is_lead)game_log("Hold: banking");if(smart.moving)return;try{r=await smart_move({to:"bank"})}catch(e0){r={failed:1,reason:(e0&&e0.reason)||e0}}if(r&&r.failed){try{r=await smart_move({map:"bank",x:0,y:-50})}catch(eB){r={failed:1}} }if(r&&r.failed){game_log("restock fail bank");return}await bank_dump();await sleep(400)}if(smart.moving)return;dest=to==="upgrade"?{to:"upgrade"}:{map:"main",x:56,y:-122};try{r=await smart_move(dest)}catch(e1){r={failed:1,reason:(e1&&e1.reason)||e1}}if(r&&r.failed){if(to==="upgrade"){game_log("restock fail upgrade");return}try{r=await smart_move({to:"potions"})}catch(eP){r={failed:1}}if(r&&r.failed){try{r=await smart_move({map:"main",x:40,y:-120})}catch(e2){r={failed:1}} }if(r&&r.failed){game_log("restock fail potions");return}}if(to!=="upgrade"){if(hold&&is_lead)game_log("Hold: buying pots");await buy_pots()}}
function parse_world(raw){var p=(""+(raw||"")).trim().replace(/[!/,]+/g," ").replace(/\s+/g," ").toUpperCase().split(" ").filter(Boolean);if(p[0]==="WORLD")p=p.slice(1);if(p.length===1&&/^(I|II|III|IV|V|PVP)$/.test(p[0]))return["US",p[0]];if(p.length>=2&&/^(US|EU|ASIA)$/.test(p[0])&&/^[A-Z0-9]+$/.test(p[1]))return[p[0],p[1]];return null}
function set_hold(v,announce){var was=hold;hold=!!v;if(hold!==was)hold_done=false;ls(hold?1:0);form_anchor=null;form_slot=null;try{stop("smart")}catch(e){}if(hold)go_s(HOME);else go_s(FARM);if(announce&&is_lead){if(hold&&!was)game_log("Hold: restocking");else if(!hold&&was)game_log("Resuming")}broadcast_state(true)}
function set_hunt(k,announce){try{stop("smart")}catch(e){}if(!k){farm_ovr=farm=null;if(announce&&is_lead)game_log("Back to the grind")}else if(FARM_BAN.indexOf(k)>=0){if(announce&&is_lead)game_log("Skip "+k+" (blacklisted)")}else if(G.monsters[k]){farm_ovr=farm=k;if(announce&&is_lead)game_log("Let's kill "+k+"!")}broadcast_state(true)}
function set_world(srv,announce){if(!srv||!srv[0]||!srv[1])return;FARM=[srv[0],srv[1]];try{stop("smart")}catch(e){}if(!hold)go_s(FARM);if(announce&&is_lead)game_log("World "+FARM[0]+"/"+FARM[1]);if(is_lead)try{send_cm(MERCHANT,{world:FARM})}catch(e2){}broadcast_state(true)}
function apply_cmd(cmd,announce){if(!cmd)return;if(cmd.type==="hold")set_hold(1,announce);else if(cmd.type==="resume")set_hold(0,announce);else if(cmd.type==="grind")set_hunt("",announce);else if(cmd.type==="hunt"&&cmd.mtype)set_hunt(cmd.mtype,announce);else if(cmd.type==="world"&&cmd.server)set_world(cmd.server,announce)}
function lead_ent(){return get_player(LEADER)||(get_party()||{})[LEADER]||null}
function leader_ok(){var L=lead_ent(),lx,ly,d;if(!(L&&!L.rip&&(L.map||L.real_x!=null||L.x!=null))){lead_blind_since=0;return false}if(get_player(LEADER)){lead_blind_since=0;return true}if(L.map&&L.map!==character.map){lead_blind_since=0;return true}if(!L.map){lead_blind_since=0;return false}lx=L.real_x!=null?L.real_x:L.x;ly=L.real_y!=null?L.real_y:L.y;d=Math.sqrt((character.real_x-lx)*(character.real_x-lx)+(character.real_y-ly)*(character.real_y-ly));if(!(d<=FORM_SMART)){lead_blind_since=0;return true}if(!lead_blind_since)lead_blind_since=Date.now();return Date.now()-lead_blind_since<20000}
function formation_pos(lead,form,angle){var dx=form.dx||0,dy=form.dy||0,x=lead.real_x!=null?lead.real_x:lead.x,y=lead.real_y!=null?lead.real_y:lead.y,c,s;if(form.face&&angle!=null&&!isNaN(angle)){c=Math.cos(angle);s=Math.sin(angle);return{map:lead.map,x:x+dx*c-dy*s,y:y+dx*s+dy*c}}return{map:lead.map,x:x+dx,y:y+dy}}
async function follow_formation(){var L,ang,lx,ly,slot,d,dx,dy,ad,sx,sy;if(hold||character.rip||!hooks||!hooks.form||farm_walking)return false;if(!leader_ok()){form_anchor=null;form_slot=null;return false}L=lead_ent();lx=L.real_x!=null?L.real_x:L.x;ly=L.real_y!=null?L.real_y:L.y;if(L.angle!=null)last_lead_angle=L.angle;ang=L.angle!=null?L.angle:last_lead_angle;ad=!form_anchor||form_anchor.map!==L.map?1e9:Math.sqrt((lx-form_anchor.x)*(lx-form_anchor.x)+(ly-form_anchor.y)*(ly-form_anchor.y));if(!form_slot||ad>FORM_REANCHOR){form_slot=formation_pos({map:L.map,real_x:lx,real_y:ly,x:lx,y:ly},hooks.form,ang);form_anchor={map:L.map,x:lx,y:ly}}slot=form_slot;dx=character.real_x-slot.x;dy=character.real_y-slot.y;d=character.map!==slot.map?1e9:Math.sqrt(dx*dx+dy*dy);if(character.map===slot.map&&d<=FORM_NEAR){if(smart.moving)try{stop("smart")}catch(e){}return true}if(character.map===slot.map&&d<=FORM_SMART){if(smart.moving)try{stop("smart")}catch(e){}if(d>FORM_FAR)move(slot.x,slot.y);return true}if(smart.moving){sx=smart.x;sy=smart.y;if(smart.map===slot.map&&sx!=null&&sy!=null&&Math.abs(sx-slot.x)+Math.abs(sy-slot.y)<50)return true;try{stop("smart")}catch(e){}}try{await smart_move({map:slot.map,x:slot.x,y:slot.y})}catch(e){game_log("form:"+((e&&e.reason)||e))}return true}
var FARM_XY={goo:{map:"main",x:0,y:180},bee:{map:"main",x:546,y:1059},crab:{map:"main",x:-1202,y:-66},snake:{map:"main",x:-82,y:1901},armadillo:{map:"main",x:526,y:1846},croc:{map:"main",x:801,y:1710},tortoise:{map:"main",x:-1124,y:1118},bat:{map:"cave",x:-194,y:-461},arcticbee:{map:"winterland",x:1082,y:-873},porcupine:{map:"desertland",x:-829,y:135},boar:{map:"winterland",x:20,y:-1109},gscorpion:{map:"desertland",x:391,y:-1422},wolfie:{map:"winterland",x:-169,y:-2026},wolf:{map:"winterland",x:433,y:-2745}};
async function go_farm(mtype){var r,c;if(!mtype||FARM_BAN.indexOf(mtype)>=0||smart.moving||farm_walking||ms(last_farm_go)<FARM_GO_MS)return;last_farm_go=new Date();farm_walking=true;set_message("Off to "+mtype);try{if(character.map==="jail"){await leave();await sleep(1000)}if(get_nearest_monster({type:mtype,max_att:farm_ovr?1e9:att_cap()}))return;try{r=await smart_move({to:mtype})}catch(e0){r={failed:1,reason:(e0&&e0.reason)||e0}}if(r&&r.failed){use("town");await sleep(2000);c=FARM_XY[mtype];if(c){try{r=await smart_move(c)}catch(e1){r={failed:1,reason:(e1&&e1.reason)||e1}}}else{try{r=await smart_move({to:mtype})}catch(e2){r={failed:1}}}if(r&&r.failed)game_log("go_farm:"+(r.reason||"fail"))}}catch(e){game_log("go_farm:"+((e&&e.message)||e))}finally{farm_walking=false}}
function farmable(t){return t&&!t.dead&&t.mtype&&t.mtype.indexOf("target")<0&&FARM_BAN.indexOf(t.mtype)<0&&!(G.monsters[t.mtype]||{}).unlist}
function ready(s){var d=G.skills[s]||{};return can_use(s)&&character.mp>=(d.mp||0)&&(!d.level||character.level>=d.level)}
function broadcast_state(force){var f=farm_ovr||farm||"-",msg;if(!is_lead)return;msg="~s h="+(hold?1:0)+" f="+f+" w="+FARM[0]+"/"+FARM[1];if(!force&&(ms(last_s)<STATE_MS||msg===last_s_msg))return;if(!psay(msg))return;last_s=new Date();last_s_msg=msg}
function parse_status(m){var out={},parts=(""+m).replace(/^~s\s*/i,"").split(/\s+/),i,kv;for(i=0;i<parts.length;i++){kv=parts[i].split("=");if(kv.length===2)out[kv[0]]=kv[1]}return out}
function parse_cmd(raw){var m=(""+(raw||"")).trim(),low=m.toLowerCase(),k,w;if(low==="!hold")return{type:"hold"};if(low==="!resume")return{type:"resume"};if(low==="!grind")return{type:"grind"};if(low.indexOf("!hunt ")===0){k=low.slice(6).replace(/[^a-z0-9_]/g,"");return k?{type:"hunt",mtype:k}:null}if(low.indexOf("!world ")===0){w=parse_world(m.slice(7));return w?{type:"world",server:w}:null}if(low.indexOf("let's kill ")===0||low.indexOf("lets kill ")===0){k=low.replace(/^let'?s kill /,"").replace(/!+$/,"").replace(/[^a-z0-9_]/g,"");return k?{type:"hunt",mtype:k}:null}if(low.indexOf("back to the grind")>=0)return{type:"grind"};return null}
function slot_ad(s){var it=character.slots[s];return it?it.name+"@"+(it.level||0):"-"}
function send_gear_ad(){var slots={mainhand:slot_ad("mainhand"),offhand:slot_ad("offhand"),helmet:slot_ad("helmet"),chest:slot_ad("chest"),pants:slot_ad("pants"),shoes:slot_ad("shoes"),gloves:slot_ad("gloves"),cape:slot_ad("cape"),belt:slot_ad("belt"),amulet:slot_ad("amulet"),ring1:slot_ad("ring1"),ring2:slot_ad("ring2")};try{send_cm(MERCHANT,{gear_ad:1,name:character.name,esize:character.esize,slots:slots})}catch(e){}last_gear_ad=new Date()}
function hear_cmd(m){if(!m)return;var from=(""+(m.name||m.from||"")).toLowerCase(),d=m.message!=null?m.message:m.data,v=null,h=null,w=null;if(from!==MERCHANT.toLowerCase())return;if(typeof d==="string"){if(d.indexOf("hold:1")>=0)v=1;else if(d.indexOf("hold:0")>=0)v=0;else if(d.indexOf("hunt:")===0)h=d.slice(5);else if(/^grind/i.test(d))h="";else try{d=JSON.parse(d)}catch(e){return}}if(typeof d==="object"&&d){if(d.dlv_ack||d.dlv_here||d.dlv_sent||d.dlv_done||d.dlv_cancel||d.dlv_meet||d.dlv_status||d.dlv_need_q||d.dlv_loot_q){hear_dlv(d);return}if(d.gear_incoming){hear_incoming(d);return}if(d.gear_offer){handle_gear_offer(d);return}if(d.gear_busy)return;if(d.world)w=d.world;if(d.hold!=null)v=d.hold;if(d.hunt!=null)h=d.hunt;if(d.grind)h=""}if(w&&is_lead){set_world(Array.isArray(w)?w:parse_world(""+w),true);return}if(h!=null&&is_lead){set_hunt(h===""?"":(""+h).toLowerCase().replace(/[^a-z0-9_]/g,""),true);return}if(v==1)set_hold(1,true);else if(v==0)set_hold(0,true)}
function hear(d){if(!d||d.message==null)return;var cmd=parse_cmd(d.message),m,from=d.from;if(cmd){apply_cmd(cmd,!from||from===character.name);return}m=(""+d.message).toLowerCase();if(m.indexOf("~s")===0){parse_status(d.message);return}if(!from||from===character.name)return;if(m.indexOf("ding")>=0)psay(pick(["Gratz!","Yes!","Proud of you."]));if(!in_arr(from,PARTY))return;if(m.indexOf("potion")>=0){psay(pick(["Ok!","On my way!","Coming!"]));if(low_pots())request_pots()}else if(m.indexOf("upgrade")>=0){psay(pick(["Ok!","On my way!","Coming!"]));rally="upgrade"}}
function busy_watch(){if(farm_walking)return;if(busy&&busy_since&&Date.now()-busy_since>BUSY_MS){busy=false;busy_since=0;try{stop("smart")}catch(e){}game_log("busy timeout")}}
function smart_watch(){if(!smart.moving){last_xy=null;return}var k=character.real_x+","+character.real_y;if(last_xy!==k){last_xy=k;last_xy_t=Date.now();return}if(Date.now()-last_xy_t>SMART_STUCK_MS){try{stop("smart")}catch(e){}game_log("smart stuck");last_xy=null}}
function handle_death(){psay(pick(["Ow.","Down!","Not today."]));setTimeout(respawn,15000);return true}
async function logistics(){if(busy||character.rip||farm_walking)return;busy=true;busy_since=Date.now();try{if(character.map==="jail"){psay("Jail. Ugh.");await leave();busy=false;busy_since=0;return}if(hold){if(go_s(HOME)){busy=false;busy_since=0;return}if(!hold_done){set_message("Hold");await restock("potions");if(low_pots()){game_log("hold:need pots");await request_pots()}offload();if(hold){hold_done=true;if(is_lead)game_log("Hold: ready");await hang_hold()}}else{set_message("Hold");await hang_hold()}}else if(go_s(FARM)){busy=false;busy_since=0;return}else{offload();if(LIVE_TEST&&is_lead&&!live_dump_done){set_message("Dump");await live_dump_pots();if(!live_dump_done){farm=desired();if(!get_nearest_monster({type:farm,max_att:farm_ovr?1e9:att_cap()})&&!smart.moving)await go_farm(farm);busy=false;busy_since=0;return}busy=false;busy_since=0;return}if(!is_lead&&!party_with_lead()){set_message("Wait party");busy=false;busy_since=0;return}if(rally==="upgrade"){set_message("Vendor");await restock("upgrade");rally=false}else if(dry_pots()&&!(LIVE_TEST&&live_dump_done&&!live_dlv_done)){set_message("Dry");await cancel_dlv("dry");await buy_pots_here();if(dry_pots()){last_req_at=0;await request_pots()}}else{if(low_pots()||(LIVE_TEST&&live_dump_done&&!live_dlv_done))await request_pots();if(LIVE_TEST&&live_dump_done&&!live_dlv_done){set_message("Wait dlv");busy=false;busy_since=0;return}if(needs_vendor()||rally){if(character.esize===0){set_message("Vendor");await restock("potions");rally=false}else rally=false}else{farm=desired();if(is_lead){if(!get_nearest_monster({type:farm,max_att:farm_ovr?1e9:att_cap()})&&!smart.moving)await go_farm(farm)}else if(leader_ok()){set_message("Form");await follow_formation()}else if(!smart.moving)await go_farm(farm)}}}}catch(e){game_log("logistics fail:"+((e&&(e.message||e.reason))||e))}busy=false;busy_since=0}
function boot_fighter(h){hooks=h||{};try{performance_trick()}catch(e){}if(LIVE_TEST){hold=false;try{ls(0)}catch(e){}}if(hold)game_log("Hold: persisted (await resume)");character.on("partym",hear);character.on("cm",hear_cmd);character.on("pm",hear_cmd);setInterval(function(){ding();use_pots();loot();offload();invite_party();busy_watch();smart_watch();broadcast_state(false);if(ms(last_gear_ad)>GEAR_AD_MS)send_gear_ad();if(dlv_pending)dlv_beacon();if(hold&&hold_done&&!smart.moving)hang_hold();if(hold&&!hold_done&&!busy&&!character.rip)logistics();if(character.rip||hold||!ATTACK_MODE||busy||smart.moving||farm_walking)return;if(LIVE_TEST&&is_lead&&(!live_dump_done||!live_dlv_done))return;if(hooks.pre_combat&&hooks.pre_combat())return;if(hooks.combat)hooks.combat(farm||desired())},250);setInterval(logistics,2500);setTimeout(logistics,1500)}
