var gear_ads={},gear_session=false,gear_offer_ids={},session_t0=0;
var GEAR_RISK=1,MIN_CHANCE=0.9,OFFER_MS=20000,READY_MS=180000,SEND_RANGE=320,MAX_SAFE=5,MAX_SAFE1=7;
var COMBINE_PRIORITY=["ringsj","hpbelt","hpamulet","stramulet","intbelt","rednose","vitring","armorring"];
var SCROLL0_ALLOW=["pants","coat","gloves","shoes","helmet","staff","shield","eears","epyjamas","eslippers","wattire","wshoes","wcap"];
var SCROLL1_DENY=["candycanesword","carrotsword"],UNIQUE=["epyjamas","eears","eslippers","mushroomstaff","candycanesword","carrotsword","xmashat"];
var PONTY_WANT=["wbook0","shield"],PONTY_MULT=1.25;
function hear_gear(m){if(!m)return;var d=m.message!=null?m.message:m.data,from=m.name||m.from;if(typeof d!=="object"||!d)return;if(d.gear_ad&&typeof in_arr==="function"&&in_arr(from,FIGHTERS)){d._t=Date.now();gear_ads[from]=d}if(d.gear_got&&d.id)gear_offer_ids[d.id]=d}
function eligible(it){var g=it&&G.items[it.name],n=it&&it.name,gr;if(!it||!g||!g.upgrade||it.l)return false;if(SCROLL1_DENY.indexOf(n)>=0)return false;gr=typeof item_grade==="function"?item_grade(it):0;if(gr===0){if(SCROLL0_ALLOW.indexOf(n)<0)return false;if(!(GEAR_RISK===1)&&UNIQUE.indexOf(n)>=0)return false;return(it.level||0)<(MAX_SAFE||5)}if(gr===1&&GEAR_RISK===1&&UNIQUE.indexOf(n)>=0)return(it.level||0)<(MAX_SAFE1||7);return false}
function find_best(name,where){var a=typeof idx==="function"?idx():[],i,best=null;for(i=0;i<a.length;i++){if(a[i].name!==name)continue;if(where&&a[i].where!==where)continue;if(!best||a[i].level>best.level)best=a[i]}return best}
function own_name(name){var a=typeof idx==="function"?idx():[],i;for(i=0;i<a.length;i++)if(a[i].name===name)return true;return false}
function locate_named(name,level){var i,it;for(i=0;i<character.items.length;i++){it=character.items[i];if(it&&it.name===name&&(level==null||(it.level||0)===level))return i}return-1}
function slot_empty(ad,slot){return!ad||!ad.slots||!ad.slots[slot]||ad.slots[slot]==="-"}
function scroll_for(it){var gr=typeof item_grade==="function"?item_grade(it):0;return gr<=0?"scroll0":gr===1?"scroll1":null}
function ponty_fair(it){var fair=typeof item_value==="function"?item_value(it):vg(it.name);return fair*((G.items[it.name]&&G.items[it.name].cash)?3:2)}
function build_gear_queue(){var q=[],i,who,ad,e;for(i=0;i<(FIGHTERS||[]).length;i++){who=FIGHTERS[i];ad=gear_ads[who];if(!ad)continue;if(slot_empty(ad,"ring1")){e=find_best("ringsj","bank")||find_best("ringsj","bag");if(e)q.push({who:who,name:"ringsj",level:e.level||0,slot:"ring1"})}if(slot_empty(ad,"ring2")){e=find_best("ringsj","bank")||find_best("ringsj","bag");if(e)q.push({who:who,name:"ringsj",level:e.level||0,slot:"ring2"})}if(slot_empty(ad,"gloves")){e=find_best("gloves","bank")||find_best("gloves","bag");if(e)q.push({who:who,name:"gloves",level:e.level||0,slot:"gloves"})}if(who==="Zarook"&&slot_empty(ad,"offhand")){e=find_best("wbook0","bank")||find_best("wbook0","bag")||find_best("shield","bank")||find_best("shield","bag");if(e)q.push({who:who,name:e.name,level:e.level||0,slot:"offhand"})}if(who==="Jazwyn"&&ad.slots&&ad.slots.belt&&ad.slots.belt.indexOf("hpbelt@0")===0){e=find_best("hpbelt","bank");if(e&&(e.level||0)>=1)q.push({who:who,name:"hpbelt",level:e.level,slot:"belt"})}if(who==="Sarene"&&ad.slots&&ad.slots.shoes&&/^shoes@[0-3]$/.test(ad.slots.shoes)){e=typeof find_ent==="function"?find_ent("shoes",4,"bank"):null;if(e)q.push({who:who,name:"shoes",level:4,slot:"shoes"})}}return q.slice(0,6)}
function fighter_ready(who){var p=get_player(who),ad=gear_ads[who];if(!p||p.rip)return false;if(p.map!==character.map||character.map!=="main")return false;if(parent.distance(character,p)>(SEND_RANGE||320))return false;if(!ad||(ad.esize||0)<1)return false;if(!session_t0||!ad._t||ad._t<session_t0)return false;return true}
function send_ok(before_name,bag_i){return!character.items[bag_i]||character.items[bag_i].name!==before_name}
async function ensure_bag_piece(name,level){var bag_i=locate_named(name,level),e,r;if(bag_i>=0)return bag_i;e=typeof find_ent==="function"?find_ent(name,level,"bank"):null;if(!e)return-1;if((character.esize||0)<1){if(gear_session)return-1;if(typeof ensure_bag==="function"&&!(await ensure_bag(1)))return-1}r=await move_ent(e,"bag");if(r==="fail")return-1;return locate_named(name,level)}
function pick_upgrade(){var best=-1,bl=99,i,it;for(i=0;i<character.items.length;i++){it=character.items[i];if(!eligible(it))continue;if((it.level||0)<bl){bl=it.level||0;best=i}}return best}
async function upgrade_one(){var i,sci,preview,it,e,pulled,scn;i=pick_upgrade();if(i<0){e=null;(typeof idx==="function"?idx():[]).forEach(function(x){if(x.where==="bank"&&eligible(x)&&(!e||x.level<e.level))e=x});if(!e)return null;pulled=await ensure_bag_piece(e.name,e.level);if(pulled<0)return"fail";i=pick_upgrade();if(i<0)return"fail"}it=character.items[i];scn=scroll_for(it);if(!scn)return"skip";sci=locate_item(scn);if(sci<0){if((await buy_scroll(scn))!=="bought")return"fail";sci=locate_item(scn);i=pick_upgrade();if(sci<0||i<0)return"fail";it=character.items[i];if(scroll_for(it)!==scn)return"fail"}try{preview=await upgrade(i,sci,null,true)}catch(err){return"fail"}if(!preview||preview.chance==null||preview.chance<(MIN_CHANCE||0.9))return"skip";if(!(await go_npc("upgrade")))return"fail";try{await upgrade(i,sci);await wait_q("upgrade");return"ok"}catch(err){return"fail"}}
async function ponty_buy(){var r,items,i,it,price,cap,best=null,spend;if(!PONTY_WANT||!PONTY_WANT.length)return null;for(i=0;i<PONTY_WANT.length;i++)if(own_name(PONTY_WANT[i]))return null;spend=character.gold-(GOLD_FLOAT||0);if(!(spend>0))return null;if((character.esize||0)<1&&typeof ensure_bag==="function"&&!(await ensure_bag(1)))return"fail";if(!(await go_npc("secondhands")))return"fail";try{r=await get_secondhands()}catch(e){return"fail"}items=(r&&r.items)||[];if(!Array.isArray(items))items=[];for(i=0;i<items.length;i++){it=items[i];if(!it||PONTY_WANT.indexOf(it.name)<0)continue;price=it.price!=null?it.price:ponty_fair(it);cap=ponty_fair({name:it.name,level:it.level||0})*(PONTY_MULT||1.25);if(price>cap||price>spend)continue;if(!best||price<best.price)best={rid:it.rid,price:price}}if(!best)return null;try{await buy_secondhand(best.rid);return"ok"}catch(e){return"fail"}}
async function start_gear_session(forced){var qi,gift,who,bag_i,id,t0,got,waited,before,p,delivered=0,k,queue;if(gear_session)return"busy";if(!(forced&&forced.length)&&!build_gear_queue().length)return"empty";gear_session=true;session_t0=Date.now();for(k in gear_ads)delete gear_ads[k];try{if(typeof hold==="function")hold();await smart_move({map:"main",x:40,y:-20});for(waited=0;waited<(READY_MS||180000);waited+=500){if((FIGHTERS||[]).some(function(n){return fighter_ready(n)}))break;await sleep(500)}queue=(forced&&forced.length)?forced:build_gear_queue();queue=queue.filter(function(g){return fighter_ready(g.who)&&slot_empty(gear_ads[g.who],g.slot)});if(!queue.length)return"not_ready";for(qi=0;qi<queue.length;qi++){gift=queue[qi];who=gift.who;id=gift.id||("g"+Date.now()+"_"+qi);bag_i=await ensure_bag_piece(gift.name,gift.level||0);if(bag_i<0)continue;if(character.map!=="main")await smart_move({map:"main",x:40,y:-20});if(!fighter_ready(who)||!slot_empty(gear_ads[who],gift.slot))continue;p=get_player(who);if(!p||parent.distance(character,p)>(SEND_RANGE||320))continue;try{send_cm(who,{gear_incoming:1,name:gift.name,level:gift.level||0,id:id})}catch(err){}await sleep(200);bag_i=locate_named(gift.name,gift.level||0);if(bag_i<0)continue;before=character.items[bag_i]&&character.items[bag_i].name;try{var sr=await send_item(who,bag_i,1);if(sr&&sr.failed)continue}catch(err){continue}if(!send_ok(before,bag_i))continue;gear_offer_ids[id]=null;try{send_cm(who,{gear_offer:1,name:gift.name,level:gift.level||0,slot:gift.slot,id:id})}catch(err){}t0=Date.now();while(Date.now()-t0<(OFFER_MS||20000)){got=gear_offer_ids[id];if(got&&got.ok===1){delivered++;break}if(got&&got.ok===0)break;await sleep(250)}}}finally{if(typeof resume==="function")resume();gear_session=false}return delivered?"done":"fail"}
try{character.on("cm",hear_gear)}catch(e){}
