var gear_ads={},gear_session=false,gear_offer_ids={},session_t0=0;
var GEAR_RISK=1,MIN_CHANCE=0.9,OFFER_MS=20000,SEND_RANGE=320,MAX_SAFE=5,MAX_SAFE1=7;
var CM_GAP_MS=700,JOB_MS=300000,GOT_MS=20000,DLV_QK="dlv_q_"+character.name;
var COMBINE_PRIORITY=["ringsj","hpbelt","hpamulet","stramulet","intbelt","rednose","vitring","armorring"];
var SCROLL0_ALLOW=["pants","coat","gloves","shoes","helmet","staff","shield","eears","epyjamas","eslippers","wattire","wshoes","wcap"];
var SCROLL1_DENY=["candycanesword","carrotsword"],UNIQUE=["epyjamas","eears","eslippers","mushroomstaff","candycanesword","carrotsword","xmashat"];
var PONTY_WANT=["wbook0","shield"],PONTY_MULT=1.25;
var dlv_q=[],dlv_active=null,last_cm_t=0,dlv_busy=false,DLV_BOOT=Date.now();
function dlv_load(){try{var r=JSON.parse(localStorage.getItem(DLV_QK)||"null"),now=Date.now(),keep=function(j){return j&&now-(j.t0||0)<(JOB_MS||300000)};if(r&&r.q){dlv_q=(r.q||[]).filter(keep);dlv_active=r.active&&keep(r.active)?r.active:null;if(dlv_active&&!dlv_q.some(function(j){return j.id===dlv_active.id}))dlv_q.unshift(dlv_active)}else{dlv_q=[];dlv_active=null}}catch(e){}}
function dlv_save(){try{localStorage.setItem(DLV_QK,JSON.stringify({q:dlv_q,active:dlv_active}))}catch(e){}}
function dlv_prune(){var now=Date.now(),n0=(dlv_q||[]).length,a0=dlv_active,keep=function(j){return j&&now-(j.t0||0)<(JOB_MS||300000)};dlv_q=(dlv_q||[]).filter(keep);if(dlv_active&&!keep(dlv_active))dlv_active=null;if(dlv_active&&!dlv_q.some(function(j){return j.id===dlv_active.id}))dlv_q.unshift(dlv_active);if(n0!==dlv_q.length||a0!==dlv_active)dlv_save()}
function dlv_has_work(){dlv_prune();return!!(dlv_active||(dlv_q&&dlv_q.length))}
function dlv_next(){var i,prefer=(typeof FIGHTERS!=="undefined"&&FIGHTERS[0])||null;if(!dlv_q.length)return null;if(prefer){for(i=0;i<dlv_q.length;i++)if(dlv_q[i].who===prefer)return dlv_q[i]}dlv_q.sort(function(a,b){return(a.t0||0)-(b.t0||0)});return dlv_q[0]}
function dlv_log(s){game_log("dlv:"+s)}
async function cm_send(to,msg){var w=(CM_GAP_MS||700)-(Date.now()-last_cm_t);if(w>0)await sleep(w);last_cm_t=Date.now();try{await send_cm(to,msg)}catch(e){dlv_log("cm_fail "+((e&&e.reason)||e))}}
function dlv_field_far(job){var c,dx,dy;if(!job)return false;if(job.map&&job.map!=="main"&&job.map!==character.map)return true;if(isFinite(job.x)&&isFinite(job.y)){dx=job.x-(character.real_x||0);dy=job.y-(character.real_y||0);if(Math.sqrt(dx*dx+dy*dy)>500)return true}if(job.farm){c=pack_center(job.farm,job.map||"main");if(c){dx=c.x-(character.real_x||0);dy=c.y-(character.real_y||0);if(Math.sqrt(dx*dx+dy*dy)>500)return true}}return false}
function dlv_phase(job){var p,map;if(!job)return"idle";if(!dlv_active||dlv_active.id!==job.id)return"queued";p=get_player(job.who);map=(p&&p.map)||job.map||"main";if(p||(isFinite(job.x)&&isFinite(job.y))){if(character.map===map&&isFinite(job.x)&&Math.abs((character.real_x||0)-job.x)+Math.abs((character.real_y||0)-job.y)<400)return"field";return"enroute"}return"buying"}
function dlv_msg(phase){return({queued:"Queued — you're next",buying:"Grabbing pots",enroute:"On my way",field:"Almost there",sending:"Handing off",none:"No open delivery"})[phase]||"On my way"}
async function dlv_tell(job,force){var ph,now=Date.now();if(!job)return;ph=dlv_phase(job);if(!force&&job._stAt&&now-job._stAt<12000&&job._st===ph)return;job._st=ph;job._stAt=now;await cm_send(job.who,{v:1,dlv_status:1,id:job.id,phase:ph,msg:dlv_msg(ph),map:character.map,x:Math.floor(character.real_x),y:Math.floor(character.real_y)});dlv_log("status "+ph+" -> "+job.who)}
function dlv_on_ping(from,d){var j=null,i;if(d&&d.id)j=dlv_find(d.id);if(!j&&dlv_active&&dlv_active.who===from)j=dlv_active;if(!j){for(i=0;i<dlv_q.length;i++)if(dlv_q[i].who===from){j=dlv_q[i];break}}if(!j){(async function(){await cm_send(from,{v:1,dlv_status:1,id:d&&d.id||null,phase:"none",msg:dlv_msg("none")})}());return}(async function(){await dlv_tell(j,true)})()}
function pack_at(map,x,y){var mons=(G.maps&&G.maps[map]&&G.maps[map].monsters)||[],i,m,b,x0,x1,y0,y1;for(i=0;i<mons.length;i++){m=mons[i];if(!m||!m.type)continue;if(m.boundary){b=m.boundary;x0=Math.min(b[0],b[2]);x1=Math.max(b[0],b[2]);y0=Math.min(b[1],b[3]);y1=Math.max(b[1],b[3]);if(x>=x0&&x<=x1&&y>=y0&&y<=y1)return m.type}else if(m.position&&Math.sqrt(Math.pow(x-m.position[0],2)+Math.pow(y-m.position[1],2))<(m.radius||180))return m.type}return null}
function pack_center(mtype,map){var mons=(G.maps&&G.maps[map||"main"]&&G.maps[map||"main"].monsters)||[],i,m,b,fb={goo:{map:"main",x:0,y:180},bat:{map:"cave",x:-194,y:-461},bee:{map:"main",x:546,y:1059},croc:{map:"main",x:801,y:1710},arcticbee:{map:"winterland",x:1082,y:-873},porcupine:{map:"desertland",x:-829,y:135},gscorpion:{map:"desertland",x:391,y:-1422},wolfie:{map:"winterland",x:-169,y:-2026},wolf:{map:"winterland",x:433,y:-2745}};for(i=0;i<mons.length;i++){m=mons[i];if(!m||m.type!==mtype)continue;if(m.boundary){b=m.boundary;return{map:map||"main",x:(b[0]+b[2])/2,y:(b[1]+b[3])/2}}if(m.position)return{map:map||"main",x:m.position[0],y:m.position[1]}}return fb[mtype]||null}
async function dlv_smart(dest,label){var fin=0,tid,r,cross=dest&&dest.map&&dest.map!==character.map,msMax=cross?180000:90000;try{stop("smart")}catch(e0){}tid=setTimeout(function(){if(!fin&&!(typeof smart!=="undefined"&&smart.moving))try{stop("smart")}catch(e1){}},msMax);try{r=await smart_move(dest);fin=1;clearTimeout(tid);if(r&&r.failed){dlv_log((label||"move")+"_fail "+((r&&r.reason)||"failed"));return false}dlv_log(label||"move");return true}catch(err){fin=1;clearTimeout(tid);dlv_log((label||"move")+"_fail "+((err&&(err.reason||err.message))||err));return false}}
async function dlv_goto(job){var x=Math.round(Number(job.x)),y=Math.round(Number(job.y)),p=get_player(job.who),map=job.map||"main",pack=job.farm||null,c,d;if(character.map==="jail"||character.map==="winter_inn"||character.map==="winter_cave"||character.map==="bank"){if(typeof ensure_main==="function")await ensure_main();else if(character.map==="bank"){try{await smart_move({map:"main",x:40,y:-20})}catch(eB){}}else if(character.map==="jail"){try{await leave();await sleep(1000)}catch(e0){}}}p=get_player(job.who);if(p&&!p.rip){map=p.map||map;x=Math.round(p.real_x);y=Math.round(p.real_y)}if(p&&!p.rip&&character.map===p.map&&parent.distance(character,p)<=(SEND_RANGE||320))return true;if(!(isFinite(x)&&isFinite(y))&&pack){c=pack_center(pack,map);if(c){map=c.map||map;x=c.x;y=c.y}}if(!(isFinite(x)&&isFinite(y)))return false;if(character.map!==map){dlv_log("goto "+map+" "+x+","+y);if(!(await dlv_smart({map:map,x:x,y:y},"mapxy"))){c=pack?pack_center(pack,map):null;if(c)await dlv_smart({map:c.map||map,x:c.x,y:c.y},"packxy")}}else if(Math.abs((character.real_x||0)-x)+Math.abs((character.real_y||0)-y)>400){dlv_log("goto "+map+" "+x+","+y);if(!(await dlv_smart({map:map,x:x,y:y},"mapxy"))){try{move(x,y);await sleep(1200)}catch(eM){}}}p=get_player(job.who);if(p&&!p.rip){d=parent.distance(character,p);if(d>(SEND_RANGE||320)){if(d<800&&character.map===p.map){try{move(p.real_x,p.real_y);await sleep(900)}catch(e4){}}else await dlv_smart({map:p.map,x:p.real_x,y:p.real_y},"player")}}return!!(get_player(job.who)&&!get_player(job.who).rip&&parent.distance(character,get_player(job.who))<=(SEND_RANGE||320))}
function hear_gear(m){if(!m)return;var d=m.message!=null?m.message:m.data,from=m.name||m.from;if(typeof d==="string")try{d=JSON.parse(d)}catch(e){return}if(typeof d!=="object"||!d)return;if(d.gear_ad&&typeof in_arr==="function"&&in_arr(from,FIGHTERS)){d._t=Date.now();gear_ads[from]=d}if(d.gear_got&&d.id)gear_offer_ids[d.id]=d;if(d.dlv_req)dlv_on_req(from,d);if(d.dlv_loc)dlv_on_loc(from,d);if(d.dlv_got)dlv_on_got(from,d);if(d.dlv_cancel||d.dlv_town)dlv_on_cancel(from,d);if(d.dlv_ping||d.dlv_status_req)dlv_on_ping(from,d)}
function dlv_find(id){var i;if(dlv_active&&dlv_active.id===id)return dlv_active;for(i=0;i<dlv_q.length;i++)if(dlv_q[i].id===id)return dlv_q[i];return null}
function dlv_on_cancel(from,d){var j=null,i;if(d&&d.id)j=dlv_find(d.id);if(!j&&dlv_active&&dlv_active.who===from)j=dlv_active;if(!j){for(i=0;i<dlv_q.length;i++)if(dlv_q[i].who===from){j=dlv_q[i];break}}if(!j)return;dlv_log("cancel id="+j.id+" from="+from+" "+(d&&d.reason||""));(async function(){await dlv_finish(j,0,d&&d.reason||"cancel")}())}
function dlv_on_req(from,d){var job,ex,i;if(!d.id||!d.kind)return;dlv_prune();ex=dlv_find(d.id);if(!ex){for(i=0;i<dlv_q.length;i++)if(dlv_q[i].who===from){ex=dlv_q[i];break}}if(ex){ex.id=d.id;ex.kind=d.kind;if(d.items)ex.items=d.items;if(d.esize!=null)ex.esize=d.esize;if(d.map!=null){ex.map=d.map;ex.x=d.x;ex.y=d.y}if(d.server)ex.server=d.server;if(d.farm!=null)ex.farm=d.farm;dlv_save();(async function(){await cm_send(from,{v:1,dlv_ack:1,id:d.id,ok:1});dlv_log("ack id="+d.id+" ok=1 dup")}());return}if(d.esize!=null&&d.esize<1){(async function(){await cm_send(from,{v:1,dlv_ack:1,id:d.id,ok:0,reason:"no_space"});dlv_log("ack id="+d.id+" ok=0 no_space")}());return}if(dlv_q.length>=8){(async function(){await cm_send(from,{v:1,dlv_ack:1,id:d.id,ok:0,reason:"busy"});dlv_log("ack id="+d.id+" ok=0 busy")}());return}job={id:d.id,who:from,kind:d.kind,items:d.items||[],map:d.map,x:d.x,y:d.y,server:d.server,esize:d.esize,farm:d.farm||null,state:"queued",t0:Date.now()};dlv_q.push(job);dlv_save();dlv_log("req id="+d.id+" kind="+d.kind+" farm="+(job.farm||"-")+" from="+from);(async function(){await cm_send(from,{v:1,dlv_ack:1,id:d.id,ok:1});dlv_log("ack id="+d.id+" ok=1");await dlv_tell(job,true)})()}
function dlv_on_loc(from,d){var j=dlv_find(d.id);if(!j||j.who!==from)return;j.map=d.map;j.x=d.x;j.y=d.y;if(d.server)j.server=d.server;if(d.farm)j.farm=d.farm;dlv_save()}
function dlv_on_got(from,d){if(dlv_active&&dlv_active.id===d.id)dlv_active._got=d}
function eligible(it){var g=it&&G.items[it.name],n=it&&it.name,gr;if(!it||!g||!g.upgrade||it.l)return false;if(SCROLL1_DENY.indexOf(n)>=0)return false;gr=typeof item_grade==="function"?item_grade(it):0;if(gr===0){if(SCROLL0_ALLOW.indexOf(n)<0)return false;if(!(GEAR_RISK===1)&&UNIQUE.indexOf(n)>=0)return false;return(it.level||0)<(MAX_SAFE||5)}if(gr===1&&GEAR_RISK===1&&UNIQUE.indexOf(n)>=0)return(it.level||0)<(MAX_SAFE1||7);return false}
function scroll_for(it){var gr=typeof item_grade==="function"?item_grade(it):0;return gr<=0?"scroll0":gr===1?"scroll1":null}
function pick_upgrade(){var best=-1,bl=99,i,it;for(i=0;i<character.items.length;i++){it=character.items[i];if(!eligible(it))continue;if((it.level||0)<bl){bl=it.level||0;best=i}}return best}
function own_name(name){var a=typeof idx==="function"?idx():[],i;for(i=0;i<a.length;i++)if(a[i].name===name)return true;return false}
function ponty_fair(it){var fair=typeof item_value==="function"?item_value(it):vg(it.name);return fair*((G.items[it.name]&&G.items[it.name].cash)?3:2)}
function locate_named(name,level){var i,it;for(i=0;i<character.items.length;i++){it=character.items[i];if(it&&it.name===name&&(level==null||(it.level||0)===level))return i}return-1}
async function ensure_bag_piece(name,level){var bag_i=locate_named(name,level),e,r;if(bag_i>=0)return bag_i;e=typeof find_ent==="function"?find_ent(name,level,"bank"):null;if(!e)return-1;if((character.esize||0)<1){if(typeof ensure_bag==="function"&&!(await ensure_bag(1)))return-1}r=await move_ent(e,"bag");if(r==="fail")return-1;return locate_named(name,level)}
async function upgrade_one(){var i,sci,preview,it,e,pulled,scn;i=pick_upgrade();if(i<0){e=null;(typeof idx==="function"?idx():[]).forEach(function(x){if(x.where==="bank"&&eligible(x)&&(!e||x.level<e.level))e=x});if(!e)return null;pulled=await ensure_bag_piece(e.name,e.level);if(pulled<0)return"fail";i=pick_upgrade();if(i<0)return"fail"}it=character.items[i];scn=scroll_for(it);if(!scn)return"skip";sci=locate_item(scn);if(sci<0){if((await buy_scroll(scn))!=="bought")return"fail";sci=locate_item(scn);i=pick_upgrade();if(sci<0||i<0)return"fail";it=character.items[i];if(scroll_for(it)!==scn)return"fail"}try{preview=await upgrade(i,sci,null,true)}catch(err){return"fail"}if(!preview||preview.chance==null||preview.chance<(MIN_CHANCE||0.9))return"skip";if(!(await go_npc("upgrade")))return"fail";try{await upgrade(i,sci);await wait_q("upgrade");return"ok"}catch(err){return"fail"}}
async function ponty_buy(){var r,items,i,it,price,cap,best=null,spend;if(!PONTY_WANT||!PONTY_WANT.length)return null;for(i=0;i<PONTY_WANT.length;i++)if(own_name(PONTY_WANT[i]))return null;spend=character.gold-(GOLD_FLOAT||0);if(!(spend>0))return null;if((character.esize||0)<1&&typeof ensure_bag==="function"&&!(await ensure_bag(1)))return"fail";if(!(await go_npc("secondhands")))return"fail";try{r=await get_secondhands()}catch(e){return"fail"}items=(r&&r.items)||[];if(!Array.isArray(items))items=[];for(i=0;i<items.length;i++){it=items[i];if(!it||PONTY_WANT.indexOf(it.name)<0)continue;price=it.price!=null?it.price:ponty_fair(it);cap=ponty_fair({name:it.name,level:it.level||0})*(PONTY_MULT||1.25);if(price>cap||price>spend)continue;if(!best||price<best.price)best={rid:it.rid,price:price}}if(!best)return null;try{await buy_secondhand(best.rid);return"ok"}catch(e){return"fail"}}
async function dlv_ensure_items(job){var i,it,need,have,buy_n,name;for(i=0;i<(job.items||[]).length;i++){it=job.items[i];name=it.name;need=it.q||1;have=quantity(name);if(have>=need)continue;buy_n=need-have;if(character.gold-(GOLD_FLOAT||0)<buy_n*((G.items[name]&&G.items[name].g)||20)){dlv_log("fail id="+job.id+" reason=gold");return false}if(character.map!=="main"&&character.map!=="bank"){try{use("town");await sleep(1500)}catch(e){}}if(!(await go_npc("potions"))){dlv_log("fail id="+job.id+" reason=potions");return false}try{await buy(name,buy_n);dlv_log("buy "+name+" "+buy_n)}catch(e){dlv_log("fail id="+job.id+" reason=buy");return false}}return true}
async function dlv_send_all(job){var i,it,idx,before,sent=[],q,left,need,got,p;p=get_player(job.who);if(!p||p.rip)return null;if(parent.distance(character,p)>(SEND_RANGE||320))return null;dlv_log("here id="+job.id+" dist="+Math.floor(parent.distance(character,p)));await cm_send(job.who,{v:1,dlv_here:1,id:job.id});for(i=0;i<(job.items||[]).length;i++){it=job.items[i];need=it.q||1;got=0;while(got<need){idx=locate_item(it.name);if(idx<0)break;q=Math.min(need-got,(character.items[idx]&&character.items[idx].q)||1);before=quantity(it.name);try{await send_item(job.who,idx,q)}catch(e){dlv_log("send_fail "+it.name);break}left=quantity(it.name);if(!(left<before))break;got+=before-left;dlv_log("send "+it.name+" "+(before-left)+" -> "+job.who)}if(got>0)sent.push({name:it.name,q:got})}return sent}
async function dlv_finish(job,ok,reason){await cm_send(job.who,{v:1,dlv_done:1,id:job.id,ok:ok?1:0,reason:reason});dlv_log("done id="+job.id+" ok="+(ok?1:0)+(reason?" "+reason:""));if(dlv_active&&dlv_active.id===job.id)dlv_active=null;dlv_q=dlv_q.filter(function(j){return j.id!==job.id});dlv_save()}
async function deliver_tick(){var job,srv,p,sent,t0,got;if(dlv_busy)return"busy";dlv_load();if(dlv_active&&Date.now()-(dlv_active.t0||0)>(JOB_MS||300000)){try{await dlv_finish(dlv_active,0,"stale")}catch(eS){}dlv_active=null}if(!dlv_active){if(!dlv_q.length)return"empty";dlv_active=dlv_next();if(!dlv_active)return"empty";dlv_active.state="active";dlv_save()}job=dlv_active;dlv_busy=true;set_message("Dlv "+job.who);try{if(typeof ensure_stand==="function")await ensure_stand(false);else if(typeof close_stand==="function")close_stand();srv=job.server;if(srv&&srv[0]&&srv[1]&&parent.server_region&&parent.server_identifier&&(parent.server_region!==srv[0]||parent.server_identifier!==srv[1])){dlv_log("hop "+srv[0]+"/"+srv[1]);dlv_save();try{change_server(srv[0],srv[1])}catch(e){}dlv_busy=false;return"hop"}if(job.esize!=null&&job.esize<1){await dlv_finish(job,0,"no_space");dlv_busy=false;return"fail"}if(!(await dlv_ensure_items(job))){await dlv_finish(job,0,"buy");dlv_busy=false;return"fail"}t0=Date.now();await dlv_tell(job,true);while(Date.now()-t0<(JOB_MS||180000)){if(!dlv_active||dlv_active.id!==job.id){dlv_busy=false;return"cancel"}await dlv_tell(job);if(job.map!=null||job.farm||get_player(job.who))await dlv_goto(job);p=get_player(job.who);if(p&&p.rip){await dlv_finish(job,0,"rip");dlv_busy=false;return"fail"}if(p&&!p.rip&&parent.distance(character,p)<=(SEND_RANGE||320)){sent=await dlv_send_all(job);if(sent&&sent.length){job._got=null;await cm_send(job.who,{v:1,dlv_sent:1,id:job.id,items:sent});dlv_log("sent id="+job.id);var w0=Date.now();while(Date.now()-w0<(GOT_MS||20000)){if(job._got||!dlv_active||dlv_active.id!==job.id)break;await sleep(250)}if(!dlv_active||dlv_active.id!==job.id){dlv_busy=false;return"cancel"}got=job._got;await dlv_finish(job,got&&got.ok===1,got&&got.ok===1?null:"no_got");dlv_busy=false;return"done"}}await sleep(1000)}await dlv_finish(job,0,"timeout");dlv_busy=false;return"fail"}catch(e){dlv_log("tick_fail "+((e&&e.message)||(e&&e.reason)||e));try{await dlv_finish(job,0,"tick")}catch(e2){}dlv_busy=false;return"fail"}}
dlv_load();
try{character.on("cm",hear_gear)}catch(e){}
