#!/usr/bin/env python3
"""
Generate a calibration GCODE file that sweeps each axis (X, Y, Z) with
well-known segment lengths and feedrates. Each axis is exercised alone so
you can record which motions produce useful "instrument" sounds.

Use this as ground truth: known movements → predictable tones → compare
our MIDI and/or audio analysis against the manifest.

Usage:
  python scripts/generate_instrument_gcode.py -o data/ground_truth/calibration.gcode
  python scripts/generate_instrument_gcode.py -o data/ground_truth/calibration.gcode --manifest data/ground_truth/manifest.json
"""

import argparse
import json
from pathlib import Path
from typing import List, Tuple


# Default: 8 feedrates (mm/min) spanning a useful range for audible stepper tones
DEFAULT_FEEDRATES = [300, 600, 900, 1200, 1500, 2000, 2500, 3000]

# Segment length (mm) per move – same for all so duration = length/feedrate * (60 sec/min)
DEFAULT_SEGMENT_MM = 20.0

# Safe origin (mm) – stay away from bed edges. Bambu P1S build ~256³
DEFAULT_ORIGIN = (50.0, 50.0, 10.0)

# Bambu P1S build volume (mm) – used to validate that we never exceed bounds
BUILD_VOLUME_P1S = (256.0, 256.0, 256.0)

# Pause between sections (seconds) so the recording clearly shows axis changes
PAUSE_SECONDS = 2.0


def emit_gcode(
    feedrates: List[float],
    segment_mm: float,
    origin: Tuple[float, float, float],
    pause_sec: float = PAUSE_SECONDS,
) -> Tuple[str, List[dict]]:
    """Generate GCODE string and a manifest of each segment (for correlation with audio/MIDI)."""
    x0, y0, z0 = origin
    lines = []
    manifest = []

    lines.append("; Instrument calibration GCODE – one axis at a time, known lengths and feedrates")
    lines.append("; Generated by scripts/generate_instrument_gcode.py")
    lines.append("; Use as ground truth: record audio and compare MIDI to this manifest.")
    lines.append("G90   ; absolute positioning")
    lines.append("G21   ; units mm")
    lines.append("")

    def add_section(axis: str, idx: int, start: float, end: float, feedrate: float):
        duration_sec = (segment_mm / feedrate) * 60.0 if feedrate > 0 else 0
        manifest.append({
            "axis": axis,
            "segment_index": len(manifest),
            "length_mm": segment_mm,
            "feedrate_mm_per_min": feedrate,
            "start_mm": start,
            "end_mm": end,
            "duration_sec": round(duration_sec, 4),
        })

    # ----- X axis only -----
    lines.append("; --- X axis: {} mm segments at feedrates {} mm/min ---".format(
        segment_mm, feedrates))
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    pos_x = x0
    for i, f in enumerate(feedrates):
        pos_x += segment_mm
        lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(pos_x, y0, z0, f))
        add_section("X", i, pos_x - segment_mm, pos_x, f)
    # Return X to start for next section
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    lines.append("")

    if pause_sec > 0:
        lines.append("; Pause {:.1f}s before Y section".format(pause_sec))
        lines.append("G4 S{:.1f}".format(pause_sec))
        lines.append("")

    # ----- Y axis only -----
    lines.append("; --- Y axis: {} mm segments at feedrates {} mm/min ---".format(
        segment_mm, feedrates))
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    pos_y = y0
    for i, f in enumerate(feedrates):
        pos_y += segment_mm
        lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, pos_y, z0, f))
        add_section("Y", i, pos_y - segment_mm, pos_y, f)
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    lines.append("")

    if pause_sec > 0:
        lines.append("; Pause {:.1f}s before Z section".format(pause_sec))
        lines.append("G4 S{:.1f}".format(pause_sec))
        lines.append("")

    # ----- Z axis only (often slower; same pattern) -----
    lines.append("; --- Z axis: {} mm segments at feedrates {} mm/min ---".format(
        segment_mm, feedrates))
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    pos_z = z0
    for i, f in enumerate(feedrates):
        pos_z += segment_mm
        lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, pos_z, f))
        add_section("Z", i, pos_z - segment_mm, pos_z, f)
    lines.append("G1 X{:.2f} Y{:.2f} Z{:.2f} F{:.0f}".format(x0, y0, z0, feedrates[0]))
    lines.append("")
    lines.append("; End calibration")

    return "\n".join(lines), manifest


def main():
    ap = argparse.ArgumentParser(
        description="Generate axis-sweep calibration GCODE (ground truth for instrument sounds)"
    )
    ap.add_argument("-o", "--output", required=True, help="Output .gcode file path")
    ap.add_argument("--manifest", help="Output manifest JSON (segment list with lengths, feedrates, durations)")
    ap.add_argument("--segment-mm", type=float, default=DEFAULT_SEGMENT_MM,
                    help="Length of each segment in mm (default: %s)" % DEFAULT_SEGMENT_MM)
    ap.add_argument("--feedrates", type=str, default=None,
                    help="Comma-separated feedrates mm/min (default: %s)" % DEFAULT_FEEDRATES)
    ap.add_argument("--origin", type=str, default="50,50,10",
                    help="X,Y,Z origin mm (default: 50,50,10)")
    ap.add_argument("--no-pause", action="store_true", help="No pause between X/Y/Z sections")
    ap.add_argument("--build-volume", type=str, default="256,256,256",
                    help="Build volume X,Y,Z in mm (default: 256,256,256 for P1S). Script fails if path would exceed it.")
    args = ap.parse_args()

    feedrates = DEFAULT_FEEDRATES
    if args.feedrates:
        feedrates = [float(x.strip()) for x in args.feedrates.split(",")]
    origin = tuple(float(x.strip()) for x in args.origin.split(","))
    if len(origin) != 3:
        raise SystemExit("--origin must be X,Y,Z (e.g. 50,50,10)")

    build_volume = tuple(float(x.strip()) for x in args.build_volume.split(","))
    if len(build_volume) != 3:
        raise SystemExit("--build-volume must be X,Y,Z (e.g. 256,256,256)")

    # Max position per axis = origin + len(feedrates) * segment_mm
    travel_per_axis = len(feedrates) * args.segment_mm
    max_x = origin[0] + travel_per_axis
    max_y = origin[1] + travel_per_axis
    max_z = origin[2] + travel_per_axis
    if max_x > build_volume[0] or max_y > build_volume[1] or max_z > build_volume[2]:
        raise SystemExit(
            "Path would exceed build volume.\n"
            "  Origin %s + %d segments * %.1f mm = max (%.1f, %.1f, %.1f) mm\n"
            "  Build volume: (%.1f, %.1f, %.1f) mm\n"
            "Use a smaller --origin, smaller --segment-mm, or larger --build-volume."
            % (list(origin), len(feedrates), args.segment_mm, max_x, max_y, max_z,
               build_volume[0], build_volume[1], build_volume[2])
        )

    gcode, manifest = emit_gcode(
        feedrates=feedrates,
        segment_mm=args.segment_mm,
        origin=origin,
        pause_sec=0.0 if args.no_pause else PAUSE_SECONDS,
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(gcode, encoding="utf-8")
    print("Wrote %s" % out_path)

    # Total duration hint
    total_sec = sum(m["duration_sec"] for m in manifest)
    total_sec += (0 if args.no_pause else PAUSE_SECONDS * 2)
    print("  Segments: %d (X=%d, Y=%d, Z=%d)" % (
        len(manifest), len(feedrates), len(feedrates), len(feedrates)))
    print("  Approx total duration (no accel): %.1f s" % total_sec)

    if args.manifest:
        manifest_path = Path(args.manifest)
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(
            json.dumps({
                "gcode_file": str(out_path.name),
                "segment_mm": args.segment_mm,
                "feedrates_mm_per_min": feedrates,
                "origin_mm": list(origin),
                "segments": manifest,
                "total_duration_sec_approx": round(total_sec, 2),
            }, indent=2),
            encoding="utf-8",
        )
        print("Wrote manifest: %s" % manifest_path)


if __name__ == "__main__":
    main()
