#!/usr/bin/env python3

import curses
import sys
import time

REFERSH_RATE = 120
TRAIL_LEN = 10

def bound(a, min, max):
    if a < min:
        return min
    if a >= max:
        return max - 1
    return a

def main(stdscr):
    curses.curs_set(0)
    height, width = stdscr.getmaxyx()
    text = ""

    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_RED, curses.COLOR_BLACK)

    while(True):
        #process input
        curses.flushinp()
        new_inp = stdscr.getch()
        if new_inp == curses.KEY_BACKSPACE:
            text = text[:-1]
        else:
            text += chr(new_inp)

        #draw text
        stdscr.clear()
        splits = text.split("\n")
        cur_line = height / 2 - len(splits) / 2
        line_start = int(width/2)
        for line in splits:
            start = int(width / 2 - len(line) / 2)
            line_start = start if start < line_start else line_start
        for line in splits:
            if len(line) > width:
                line = line[:width]
            stdscr.addstr(int(cur_line), line_start, line, curses.color_pair(1))
            cur_line += 1
        stdscr.addstr("|", curses.color_pair(2))

        stdscr.refresh()

        #wait
        time.sleep(1.0 / REFERSH_RATE)

if __name__=='__main__':
    curses.wrapper(main)

