"""Degree bookkeeping for polynomial Galerkin Lyapunov candidates."""

from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Iterable


@dataclass(frozen=True)
class DegreeContribution:
    """One homogeneous degree generated by a part of the Galerkin vector field."""

    source_degree: int
    generator_part: str
    output_degree: int


def _validate_degrees(degrees: Iterable[int]) -> tuple[int, ...]:
    normalized = tuple(sorted(set(degrees)))
    if not normalized:
        raise ValueError("at least one homogeneous degree is required")
    if any(degree <= 0 or degree % 2 for degree in normalized):
        raise ValueError("candidate degrees must be positive even integers")
    return normalized


def _validate_dissipation_degrees(degrees: Iterable[int]) -> tuple[int, ...]:
    normalized = tuple(sorted(set(degrees)))
    if not normalized:
        raise ValueError("at least one dissipation degree is required")
    if any(degree <= 0 for degree in normalized):
        raise ValueError("dissipation degrees must be positive integers")
    return normalized


def generator_degree_profile(
    candidate_degrees: Iterable[int],
) -> tuple[DegreeContribution, ...]:
    """Return degrees produced by linear and quadratic Galerkin dynamics.

    For z_t = -nu A z - B(z, z), the linear vector field preserves polynomial
    degree and the quadratic vector field raises it by one.
    """
    validated = _validate_degrees(candidate_degrees)
    contributions = [
        DegreeContribution(degree, "linear", degree) for degree in validated
    ]
    contributions.extend(
        DegreeContribution(degree, "quadratic", degree + 1)
        for degree in validated
    )
    return tuple(contributions)


def highest_nonlinear_degree(candidate_degrees: Iterable[int]) -> int:
    """Return the largest degree generated by the quadratic nonlinearity."""
    return max(
        contribution.output_degree
        for contribution in generator_degree_profile(candidate_degrees)
        if contribution.generator_part == "quadratic"
    )


def quadratic_generator_output_degree(source_degree: int) -> int:
    """Return the output degree from differentiating through ``B(z, z)``."""
    if source_degree <= 0:
        raise ValueError("source degree must be positive")
    return source_degree + 1


def nonlinear_degree_is_dissipation_supported(
    candidate_degrees: Iterable[int],
    dissipation_degrees: Iterable[int],
) -> bool:
    """Check whether dissipation includes the highest nonlinear output degree.

    This is necessary bookkeeping, not a sufficient sign or coercivity test.
    """
    dissipation = _validate_dissipation_degrees(dissipation_degrees)
    return highest_nonlinear_degree(candidate_degrees) in dissipation
